/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dao.DistritoDao;
import FormatacaoCampos.PermitirInteiros;
import Modelo.Areacurso;
import Modelo.Areaespecializacao;
import Modelo.Distrito;
import Modelo.Formador;
import Modelo.Localidade;
import Persistencia.AreacursoJpaController;
import Persistencia.AreaespecializacaoJpaController;
import Persistencia.FormadorJpaController;
import Persistencia.LocalidadeJpaController;
import Persistencia.exceptions.IllegalOrphanException;
import Persistencia.exceptions.PreexistingEntityException;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author MASSINGUE
 */
public class CadastrarFormador extends javax.swing.JDialog {

    /**
     * Creates new form CadastrarFormador
     */
    public CadastrarFormador(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            prenchercomboDistrito();
            prenchercomboArea();
            prenchercomboArea1();
            prenchercomboArea2();
            datanasc.setDateFormatString("dd/MM/yyyy");
            txtExperiencia.setDocument(new PermitirInteiros());
            txtnuit.setDocument(new PermitirInteiros());
            txttelefone.setDocument(new PermitirInteiros());
            txttelemovel.setDocument(new PermitirInteiros());
            masculino.setSelected(true);
            naoINEFP.setSelected(true);
            naoPsicopedagogia.setSelected(true);
            
//            SimContOutrem.setEnabled(false);
//            simDesempregado.setEnabled(false);
//            //simINEFP.setEnabled(false);
//            simLicenciatura.setEnabled(false);
//            simOutro.setEnabled(false);
//            simSecundario.setEnabled(false);
//            simTecnico.setEnabled(false);
           // simDesempregado.setSelected(false);
            
             Dimension centro=Toolkit.getDefaultToolkit().getScreenSize();
            this.setLocation((centro.width-getWidth())/2 ,(centro.height-getHeight())/2);
        } catch (SQLException ex) {
            Logger.getLogger(CadastrarFormador.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botaoguardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        masculino = new javax.swing.JRadioButton();
        femenino = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        txtbilhete = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtnuit = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        combodistrito = new javax.swing.JComboBox();
        jLabel30 = new javax.swing.JLabel();
        txtmorada = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txttelemovel = new javax.swing.JTextField();
        txttelefone = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        botaanexar = new javax.swing.JButton();
        datanasc = new com.toedter.calendar.JDateChooser();
        txtanexocv = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtprofissao = new javax.swing.JTextField();
        SimContOutrem = new javax.swing.JRadioButton();
        jLabel11 = new javax.swing.JLabel();
        simEmpresario = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtEntidadeempregadora = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        txtEmpresa = new javax.swing.JTextField();
        txtExperiencia = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        naoINEFP = new javax.swing.JRadioButton();
        simINEFP = new javax.swing.JRadioButton();
        jLabel50 = new javax.swing.JLabel();
        naoPsicopedagogia = new javax.swing.JRadioButton();
        simPsicopedagogia = new javax.swing.JRadioButton();
        jLabel49 = new javax.swing.JLabel();
        txtoutrasituacao = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        simLicenciatura = new javax.swing.JRadioButton();
        simSecundario = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        txtareaformacao = new javax.swing.JTextField();
        txtnivel = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        simTecnico = new javax.swing.JRadioButton();
        txtCurso = new javax.swing.JTextField();
        jLabel37 = new javax.swing.JLabel();
        jLabel58 = new javax.swing.JLabel();
        jLabel59 = new javax.swing.JLabel();
        jLabel62 = new javax.swing.JLabel();
        simOutro = new javax.swing.JRadioButton();
        jLabel61 = new javax.swing.JLabel();
        txtespecifique = new javax.swing.JTextField();
        jLabel63 = new javax.swing.JLabel();
        simBasico = new javax.swing.JRadioButton();
        jLabel64 = new javax.swing.JLabel();
        txtnivelbasico = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        Comboarea1 = new javax.swing.JComboBox();
        comboarea2 = new javax.swing.JComboBox();
        comboarea3 = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));

        botaoguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/save1.png"))); // NOI18N
        botaoguardar.setText("Guardar");
        botaoguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoguardarActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Erase.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(botaoguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 266, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoguardar)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome Completo:");

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup3.add(masculino);
        masculino.setText("Masculino");

        buttonGroup3.add(femenino);
        femenino.setText("Feminino");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(masculino)
                .addGap(18, 18, 18)
                .addComponent(femenino)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(masculino)
                    .addComponent(femenino))
                .addContainerGap())
        );

        jLabel5.setText("Email:");

        jLabel7.setText("Nuit:");

        jLabel14.setText("Comunidade:");

        txtemail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtemailActionPerformed(evt);
            }
        });

        jLabel15.setText("B.I/Pass:");

        jLabel30.setText("Morada:");

        jLabel32.setText("Telemovel:");

        jLabel16.setText("Telefone:");

        jLabel3.setText("Sexo:");

        botaanexar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/anexo4.png"))); // NOI18N
        botaanexar.setText("Anexar CV");
        botaanexar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaanexarActionPerformed(evt);
            }
        });

        jLabel13.setText("Anexar Curricula Vitae:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtnome)
                            .addComponent(jLabel2)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel32)
                            .addComponent(jLabel15)
                            .addComponent(txttelemovel)
                            .addComponent(txtbilhete, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel16)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtnuit)
                                    .addComponent(jLabel5)
                                    .addComponent(datanasc, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                                    .addComponent(txtemail)
                                    .addComponent(txttelefone)))))
                    .addComponent(jLabel3))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(botaanexar, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(jLabel30)
                            .addComponent(txtmorada)
                            .addComponent(combodistrito, 0, 212, Short.MAX_VALUE)
                            .addComponent(txtanexocv)
                            .addComponent(jLabel14))
                        .addGap(192, 192, 192))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel13)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combodistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel30)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtmorada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(148, 148, 148)
                        .addComponent(botaanexar)
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(datanasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(23, 23, 23)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtbilhete, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel32)
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(txttelemovel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txttelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtnuit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtanexocv, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())))))
        );

        jLabel8.setText("Data Nasc:");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(241, 241, 241)
                .addComponent(jLabel8)
                .addContainerGap(628, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(11, 11, 11)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel8)
                .addContainerGap(364, Short.MAX_VALUE))
            .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel6Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(34, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Dados Pessoais", jPanel6);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel10.setText("Profissao:");

        SimContOutrem.setText("Sim");
        SimContOutrem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SimContOutremActionPerformed(evt);
            }
        });

        jLabel11.setText("Empre.Cont.Outrem:");

        simEmpresario.setText("Sim");
        simEmpresario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simEmpresarioActionPerformed(evt);
            }
        });

        jLabel12.setText("Conta Propria/Empresario:");

        jLabel19.setText("Anos Experiencia:");

        jLabel26.setText("Entidade Formadora:");

        txtEntidadeempregadora.setEditable(false);

        jLabel27.setText("Nome Empresa:");

        txtEmpresa.setEditable(false);

        jLabel34.setText("Outra situacao:");

        buttonGroup1.add(naoINEFP);
        naoINEFP.setText("Nao");

        buttonGroup1.add(simINEFP);
        simINEFP.setText("Sim");

        jLabel50.setText("Formador do INEFP:");

        buttonGroup2.add(naoPsicopedagogia);
        naoPsicopedagogia.setText("Nao");

        buttonGroup2.add(simPsicopedagogia);
        simPsicopedagogia.setText("Sim");

        jLabel49.setText("Form.Psicopedagogia:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10)
                            .addComponent(txtprofissao, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SimContOutrem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtEntidadeempregadora))
                        .addContainerGap())
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(simEmpresario, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel34))
                                .addGap(62, 62, 62))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(txtoutrasituacao)
                                .addGap(26, 26, 26)))
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel27)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel19)
                                .addGap(53, 53, 53))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(simINEFP, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(naoINEFP, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel12Layout.createSequentialGroup()
                                        .addComponent(simPsicopedagogia, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(naoPsicopedagogia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap())
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addComponent(jLabel50)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel49)
                                .addGap(31, 31, 31))))))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel26)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtEntidadeempregadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtprofissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SimContOutrem))))
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel27)))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel19)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simEmpresario)
                    .addComponent(txtEmpresa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtExperiencia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(jLabel50)
                    .addComponent(jLabel49))
                .addGap(9, 9, 9)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simINEFP)
                    .addComponent(naoINEFP)
                    .addComponent(naoPsicopedagogia)
                    .addComponent(simPsicopedagogia)
                    .addComponent(txtoutrasituacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(47, Short.MAX_VALUE))
        );

        jLabel9.setText("Situacao Profissional:");

        jLabel28.setText("Habilitacoes Literarias:");

        jPanel13.setBackground(new java.awt.Color(255, 255, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        simLicenciatura.setText("Sim");
        simLicenciatura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simLicenciaturaActionPerformed(evt);
            }
        });

        simSecundario.setText("Sim");
        simSecundario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simSecundarioActionPerformed(evt);
            }
        });

        jLabel31.setText("Licenciatura:");

        txtareaformacao.setEditable(false);

        txtnivel.setEditable(false);

        jLabel35.setText("Secundario:");

        jLabel36.setText("C.Tecnico:");

        simTecnico.setText("Sim");
        simTecnico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simTecnicoActionPerformed(evt);
            }
        });

        txtCurso.setEditable(false);

        jLabel37.setText("Area de Formacao:");

        jLabel58.setText("Nivel Secundario:");

        jLabel59.setText("Curso:");

        jLabel62.setText("Outro");

        simOutro.setText("Sim");
        simOutro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simOutroActionPerformed(evt);
            }
        });

        jLabel61.setText("Especifique:");

        txtespecifique.setEditable(false);

        jLabel63.setText("Basico");

        simBasico.setText("Sim");
        simBasico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simBasicoActionPerformed(evt);
            }
        });

        jLabel64.setText("Nivel Basico:");

        txtnivelbasico.setEditable(false);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel63, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(simBasico, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34)
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel64, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnivelbasico)))
                    .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel13Layout.createSequentialGroup()
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel31))
                                .addComponent(simLicenciatura, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtareaformacao, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel36, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simTecnico, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel59, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simSecundario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel13Layout.createSequentialGroup()
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel62, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(simOutro, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel61, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtespecifique)))))
                .addGap(22, 22, 22))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel13Layout.createSequentialGroup()
                        .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel31)
                            .addComponent(jLabel37))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(simLicenciatura))
                    .addComponent(txtareaformacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(jLabel59))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simTecnico)
                    .addComponent(txtCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(jLabel58))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simSecundario)
                    .addComponent(txtnivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel63)
                    .addComponent(jLabel64))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simBasico)
                    .addComponent(txtnivelbasico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel62)
                    .addComponent(jLabel61))
                .addGap(5, 5, 5)
                .addGroup(jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simOutro)
                    .addComponent(txtespecifique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("Especializacao 1:");

        jLabel4.setText("Especializacao2:");

        jLabel6.setText("Especializacao3:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Comboarea1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboarea2, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(comboarea3, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Comboarea1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboarea2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboarea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addComponent(jLabel28)
                .addContainerGap(185, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel9)
                .addContainerGap(796, Short.MAX_VALUE))
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                    .addContainerGap(616, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel28))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel10Layout.createSequentialGroup()
                    .addGap(35, 35, 35)
                    .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        jTabbedPane1.addTab("Situacao Profissional", jPanel10);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 13, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoguardarActionPerformed
       verificarcampos();
         //cadastrar();

    }//GEN-LAST:event_botaoguardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void simEmpresarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simEmpresarioActionPerformed
        if(simEmpresario.isSelected()){
            txtEmpresa.setEditable(true);}
        else
        txtEmpresa.setEditable(false);
    }//GEN-LAST:event_simEmpresarioActionPerformed

    private void txtemailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtemailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtemailActionPerformed

    private void SimContOutremActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SimContOutremActionPerformed
        if(SimContOutrem.isSelected())
            txtEntidadeempregadora.setEditable(true);
        else{
            txtEntidadeempregadora.setText(" ");
            txtEntidadeempregadora.setEditable(false);
        }
    }//GEN-LAST:event_SimContOutremActionPerformed

    private void botaanexarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaanexarActionPerformed
    
       
    }//GEN-LAST:event_botaanexarActionPerformed

    private void simLicenciaturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simLicenciaturaActionPerformed
        if(simLicenciatura.isSelected()){
            txtareaformacao.setEditable(true);}
        else
        txtareaformacao.setEditable(false);
    }//GEN-LAST:event_simLicenciaturaActionPerformed

    private void simSecundarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simSecundarioActionPerformed
        if(simSecundario.isSelected()){
            txtnivel.setEditable(true);}
        else
        txtnivel.setEditable(false);
    }//GEN-LAST:event_simSecundarioActionPerformed

    private void simTecnicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simTecnicoActionPerformed
        if(simTecnico.isSelected())
        txtCurso.setEditable(true);
        else{
            txtCurso.setEditable(false);
        }
    }//GEN-LAST:event_simTecnicoActionPerformed

    private void simOutroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simOutroActionPerformed
        if(simOutro.isSelected())
        txtespecifique.setEditable(true);
        else{
            txtespecifique.setEditable(false);
        }
    }//GEN-LAST:event_simOutroActionPerformed

    private void simBasicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simBasicoActionPerformed
         txtnivelbasico.setEditable(true);
    }//GEN-LAST:event_simBasicoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastrarFormador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastrarFormador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastrarFormador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastrarFormador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                CadastrarFormador dialog = new CadastrarFormador(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox Comboarea1;
    private javax.swing.JRadioButton SimContOutrem;
    private javax.swing.JButton botaanexar;
    private javax.swing.JButton botaoguardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.JComboBox comboarea2;
    private javax.swing.JComboBox comboarea3;
    private javax.swing.JComboBox combodistrito;
    private com.toedter.calendar.JDateChooser datanasc;
    private javax.swing.JRadioButton femenino;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel61;
    private javax.swing.JLabel jLabel62;
    private javax.swing.JLabel jLabel63;
    private javax.swing.JLabel jLabel64;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JRadioButton masculino;
    private javax.swing.JRadioButton naoINEFP;
    private javax.swing.JRadioButton naoPsicopedagogia;
    private javax.swing.JRadioButton simBasico;
    private javax.swing.JRadioButton simEmpresario;
    private javax.swing.JRadioButton simINEFP;
    private javax.swing.JRadioButton simLicenciatura;
    private javax.swing.JRadioButton simOutro;
    private javax.swing.JRadioButton simPsicopedagogia;
    private javax.swing.JRadioButton simSecundario;
    private javax.swing.JRadioButton simTecnico;
    private javax.swing.JTextField txtCurso;
    private javax.swing.JTextField txtEmpresa;
    private javax.swing.JTextField txtEntidadeempregadora;
    private javax.swing.JTextField txtExperiencia;
    private javax.swing.JTextField txtanexocv;
    private javax.swing.JTextField txtareaformacao;
    private javax.swing.JTextField txtbilhete;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtespecifique;
    private javax.swing.JTextField txtmorada;
    private javax.swing.JTextField txtnivel;
    private javax.swing.JTextField txtnivelbasico;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtnuit;
    private javax.swing.JTextField txtoutrasituacao;
    private javax.swing.JTextField txtprofissao;
    private javax.swing.JTextField txttelefone;
    private javax.swing.JTextField txttelemovel;
    // End of variables declaration//GEN-END:variables

     private void prenchercomboDistrito() throws SQLException {
       
             List<Localidade> localidades = new LocalidadeJpaController().findLocalidadeEntities();
                combodistrito.removeAllItems();
                for (Localidade d : localidades) {
                         combodistrito.addItem(d);
               }
               
                   
       
    }
     
      private void prenchercomboArea1() throws SQLException {
       
             List<Areacurso> cursos = new AreacursoJpaController().findAreacursoEntities();
                Comboarea1.removeAllItems();
                for (Areacurso d : cursos) {
                         Comboarea1.addItem(d);
               }
               
                   
       
    }
     
       private void prenchercomboArea2() throws SQLException {
       
             List<Areacurso> cursos = new AreacursoJpaController().findAreacursoEntities();
                comboarea2.removeAllItems();
                for (Areacurso d : cursos) {
                         comboarea2.addItem(d);
               }
               
                   
       
    }
        private void prenchercomboArea() throws SQLException {
       
             List<Areacurso> cursos = new AreacursoJpaController().findAreacursoEntities();
                comboarea3.removeAllItems();
                for (Areacurso d : cursos) {
                         comboarea3.addItem(d);
               }
               
                   
       
    }
     
     
     private void cadastrar(){
        try {        
            Formador f=new Formador();
            f.setFormador(txtnome.getText());
             if(!txtExperiencia.getText().trim().equals("")){
                 f.setAnosexperiencia(Integer.valueOf(txtExperiencia.getText()));
            } else 
            f.setAnosexperiencia(0);
            f.setDatanasc(new Date(datanasc.getDate().getTime()));
            f.setIddistrito(new Localidade(combodistrito.getSelectedIndex()+1));
            if(masculino.isSelected()){
                f.setSexo(true);}
            else
                if(femenino.isSelected()){
                    f.setSexo(false);}
            
            f.setEmail(txtemail.getText());
            f.setMorada(txtmorada.getText());
            f.setBi(txtbilhete.getText());
            if(!txtnuit.getText().trim().equals("")){
                 f.setNuit(Integer.valueOf(txtnuit.getText()));
            } else 
            f.setNuit(0);
            if(!txttelemovel.getText().trim().equals("")){
                 f.setTelemovel(Integer.valueOf(txttelemovel.getText()));
            } else 
            f.setTelemovel(0);
            
            if(!txttelefone.getText().trim().equals("")){
                 f.setTelefone(Integer.valueOf(txttelefone.getText()));
            } else 
            f.setTelefone(0);
            f.setProfissao(txtprofissao.getText());
            if(SimContOutrem.isSelected()){
                f.setEmpregado(true);
                f.setEntidadeempregadora(txtEntidadeempregadora.getText()); 
            } else{
                f.setEmpregado(false);}
            if(simEmpresario.isSelected()){
                f.setEmpresario(true);
                f.setNomeempresa(txtEmpresa.getText());
            } 
            else{
               f.setEmpresario(false);
            }
            
              f.setOutrosituacao(txtoutrasituacao.getText());
            
             
            if(simLicenciatura.isSelected()){
                f.setLicenciatura(true);
                f.setAreaformacao(txtareaformacao.getText());
            }else
                {
                f.setLicenciatura(false);
            }
               if(simSecundario.isSelected()){
                f.setSecundario(true);
                f.setNivel(txtnivel.getText());
            }else
                {
                f.setSecundario(false);
            }
               if(simTecnico.isSelected()){
                f.setTecnico(true);
                f.setCurso(txtCurso.getText());
            }else
                {
                f.setTecnico(false);
            }
               if(simOutro.isSelected()){
                f.setOutro(true);
                f.setEspecifique(txtespecifique.getText());
            }else
                {
                f.setOutro(false);
            }
                if(simINEFP.isSelected()){
                f.setFormadorINEFP(true);
               
            } else 
                  if(naoINEFP.isSelected()){
                   f.setFormadorINEFP(false);
             }
                 if(simPsicopedagogia.isSelected()){
                f.setPsicopedagogia(true);
               
            } else 
                  if(naoPsicopedagogia.isSelected()){
                
                    f.setPsicopedagogia(false);
              }
                 if(simBasico.isSelected()){
                    f.setBasico(true);
                    f.setNivelbasico(txtnivelbasico.getText());
                 }
                 else {
                    f.setBasico(false);
                    f.setNivelbasico(" ");
                 }
 //            
             File fi = null;
             //converte o objeto file em array de bytes
           
 
             //f.setCurricula(bytes);
         
         
         
         new FormadorJpaController().create(f);
           
          // JOptionPane.showMessageDialog(null, "Formadoradastrado com sucesso");
           Areaespecializacao as=new Areaespecializacao();
           as.setIdformador(f.getIdformador());
           as.setIdarea1(new Areacurso(Comboarea1.getSelectedIndex()+1));
           as.setIdarea2(new Areacurso(comboarea2.getSelectedIndex()+1));
           as.setIdarea3(new Areacurso(comboarea3.getSelectedIndex()+1));
               new AreaespecializacaoJpaController().create(as);
               JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
               limparcampos();
        } catch (IllegalOrphanException ex) {
            Logger.getLogger(CadastrarFormador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (PreexistingEntityException ex) {
            Logger.getLogger(CadastrarFormador.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(CadastrarFormador.class.getName()).log(Level.SEVERE, null, ex);
        }
       
                
            
        
       
     
     }
     
     
    public void escolhearquivo() {
//   
       JFileChooser arquivo = new JFileChooser();    
          arquivo.setDialogTitle("Selecione a CV");    
          arquivo.setFileSelectionMode(JFileChooser.FILES_ONLY);    
          FileNameExtensionFilter filter = new FileNameExtensionFilter("PDF & .DOC", new String[]{"pdf","doc"});    
          arquivo.setFileFilter(filter);          
          arquivo.setAcceptAllFileFilterUsed(false);  
          arquivo.setMultiSelectionEnabled(false);    
          File file = new File("user.dir");    
          int option = arquivo.showOpenDialog(this);
       //   PessoasDAO pDao = new PessoasDAO();
          if(option == JFileChooser.APPROVE_OPTION) {
                     
               String caminhoArquivo = "";
               caminhoArquivo = arquivo.getSelectedFile().getAbsolutePath();
               file = arquivo.getSelectedFile();  
               String nomeArquivo = file.getName();  
               int e = nomeArquivo.lastIndexOf(".");  
               String extensao = nomeArquivo.substring(e);
               Image image = null;
               try {               
                   image = ImageIO.read(file);
               } catch (IOException ex) {
                   Logger.getLogger(CadastrarFormador.class.getName()).log(Level.SEVERE, null, ex);
               }
               
               if(extensao.equals(".pdf") || extensao.equals(".PDF")){
                   //  lblFoto.setIcon(new ImageIcon(arquivo.getSelectedFile().getAbsolutePath()));
                     txtanexocv.setText(caminhoArquivo);
                     
                             
                   //  lblFoto.setIcon(new ImageIcon(image.getScaledInstance(lblFoto.getWidth(),lblFoto.getHeight(), image.SCALE_DEFAULT)));  
               }else{  
                   JOptionPane.showMessageDialog(null, "Arquivo não suportado", "Erro", JOptionPane.ERROR_MESSAGE);      
               }      
 //     }
              
    
  
          }
         
    }
   
 
     
//     public void anexarcv(){
//     
//         JFileChooser file = new JFileChooser(); 
//          file.setFileSelectionMode(JFileChooser.FILES_ONLY);
//          int i= file.showSaveDialog(null);
//        if (i==1){
//            txtanexocv.setText("");
//        } else {
//            File arquivo = file.getSelectedFile();
//           txtanexocv.setText(arquivo.getPath());
//           
//        }
//     }
     
     private void limparcampos(){
       txtCurso.setText("");
       txtEmpresa.setText("");
       txtEntidadeempregadora.setText("");
//       txtEspecializacao2.setText("");
       txtExperiencia.setText("");
//       txtanexocv.setText("");
       txtareaformacao.setText("");
       txtbilhete.setText("");
       txtemail.setText("");
//       txtespecializacao.setText("");
//       txtespecializacao3.setText("");
       txtespecifique.setText("");
       txtmorada.setText("");
       txtnivel.setText("");
       txtnome.setText("");
       txtnuit.setText("");
       txtprofissao.setText("");
       txttelefone.setText("");
       txttelemovel.setText("");
       combodistrito.setSelectedIndex(0);
       SimContOutrem.setSelected(false);
       txtnivelbasico.setText("");
       simINEFP.setSelected(false);
       simLicenciatura.setSelected(false);
       simOutro.setSelected(false);
       simPsicopedagogia.setSelected(false);
       simSecundario.setSelected(false);
       simTecnico.setSelected(false);
       Comboarea1.setSelectedIndex(0);
       comboarea2.setSelectedIndex(0);
       comboarea3.setSelectedIndex(0);
       combodistrito.setSelectedIndex(0);
     
     
     }
     
     private void verificarcampos(){
           if(txtnome.getText().trim().equals("")){
              txtnome.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo Nome e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
               
//              if(!datanasc.getDate().getTime().tr){
//             // txtnome.requestFocus();
//              JOptionPane.showMessageDialog(null,"Campo Sexo e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
//              return;
//           }
           
           
            if(txtbilhete.getText().trim().equals("")){
              txtbilhete.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo B.I/Pass e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           } 
             if(txtprofissao.getText().trim().equals("")){
              txtprofissao.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo B.I/Pass e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           } 
            
            
             if(txttelemovel.getText().trim().equals("")){
              txttelemovel.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo Telemovel e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
             if(txtExperiencia.getText().trim().equals("")){
              txtExperiencia.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo Anos de Experiencia e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
             
             
             if(txtnuit.getText().trim().equals("")){
              txtnuit.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo Nuit e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
             
//              if(txtespecializacao.getText().trim().equals("")){
//              txtespecializacao.requestFocus();
//              JOptionPane.showMessageDialog(null,"Campo Especializacao e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
//              return;
//           }
//                if(txtEspecializacao2.getText().trim().equals("")){
//              txtEspecializacao2.requestFocus();
//              JOptionPane.showMessageDialog(null,"Campo especializacao2 e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
//              return;
//           }
//                 if(txtespecializacao3.getText().trim().equals("")){
//              txtespecializacao3.requestFocus();
//              JOptionPane.showMessageDialog(null,"Campo especializacao3 e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
//              return;
//           }
                  if(datanasc.getDate()==null){
                    datanasc.requestFocus();
              JOptionPane.showMessageDialog(null,"Campo data nascimento e obrigatorio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
                 
                 
             cadastrar();
             
           
       }
     
     
     
     
}
