/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dao.DistritoDao;
import Dao.FormandoDao;
import Dao.LocalidadeDao;
import Modelo.Areadeformacao;
import Modelo.Curso;
import Modelo.Cursoformacao;
import Modelo.Distrito;
import Modelo.Finscritos;
import Modelo.Formando;
import Modelo.Localidade;
import Modelo.Relactividadeprof;
import Modelo.Relestadocivil;
import Modelo.Relformandoarea;
import Persistencia.AreadeformacaoJpaController;
import Persistencia.CursoJpaController;
import Persistencia.CursoformacaoJpaController;
import Persistencia.DistritoJpaController;
import Persistencia.FinscritosJpaController;
import Persistencia.FormandoJpaController;
import Persistencia.LocalidadeJpaController;
import Persistencia.exceptions.IllegalOrphanException;
import Persistencia.exceptions.NonexistentEntityException;
import Persistencia.exceptions.PreexistingEntityException;
import java.awt.Image;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.SQLException;
import java.text.BreakIterator;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import metodo.RelatorioCtr;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MASSINGUE
 */
public class GerirCurso extends javax.swing.JInternalFrame {

//    Formando formando = new Formando();
    Curso curso = new Curso();

    /**
     * Creates new form GerirFormando
     */
    public GerirCurso() {
            initComponents();
          //  prenchercomboDistrito();
          //  prenchercomboLocalidade();
            listarCursos();
//           
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtPesquisaNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxpesquisalocalidade = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadecurso = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botaoEdit = new javax.swing.JButton();
        botaoDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        botaprevisualizar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        txtPesquisaNome1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        ComboBoxpesquisalocalidade3 = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadecurso1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        botaoEdit1 = new javax.swing.JButton();
        botaoDelete1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        botaprevisualizar1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listadeformandolocalidade1 = new javax.swing.JTable();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel21 = new javax.swing.JPanel();
        ComboBoxpesquisadistrito2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        ComboBoxpesquisalocalidade2 = new javax.swing.JComboBox();

        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseReleased(evt);
            }
        });

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPesquisaNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaNomeCaretUpdate(evt);
            }
        });

        jLabel2.setText("Pesquisar por Codigo:");

        jLabel6.setText("Comunidade:");

        ComboBoxpesquisalocalidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisalocalidadeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ComboBoxpesquisalocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisalocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadecurso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Codigo Curso", "Nome Curso", "Comunidade", "Data Inicio", "Data Fim", " Matriculado H", " Matriculado M", " Matriculado Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadecurso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadecursoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listadecurso);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1324, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo.png"))); // NOI18N
        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001_45.png"))); // NOI18N
        botaoEdit.setText("Modificar");
        botaoEdit.setEnabled(false);
        botaoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditActionPerformed(evt);
            }
        });

        botaoDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001_49.png"))); // NOI18N
        botaoDelete.setText("Eliminar");
        botaoDelete.setEnabled(false);
        botaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Erase.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        botaprevisualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/print.png"))); // NOI18N
        botaprevisualizar.setText("Imprimir");
        botaprevisualizar.setEnabled(false);
        botaprevisualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaprevisualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaprevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 653, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaprevisualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(botaoEdit)
                        .addComponent(botaoDelete))))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registo de Curso", jPanel9);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));

        jPanel11.setBackground(new java.awt.Color(102, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPesquisaNome1.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaNome1CaretUpdate(evt);
            }
        });

        jLabel3.setText("Pesquisar por Codigo:");

        jLabel10.setText("Comunidade:");

        ComboBoxpesquisalocalidade3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisalocalidade3ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPesquisaNome1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(ComboBoxpesquisalocalidade3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaNome1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisalocalidade3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadecurso1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Codigo Curso", "Nome Curso", "Comunidade", "Mestre", "Data Inicio", "Data Fim", " Matriculado Total", "H", "M"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadecurso1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadecurso1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listadecurso1);
        listadecurso1.getColumnModel().getColumn(4).setHeaderValue("Mestre");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1324, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel14.setBackground(new java.awt.Color(0, 153, 255));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo.png"))); // NOI18N
        jButton2.setText("Novo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        botaoEdit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001_45.png"))); // NOI18N
        botaoEdit1.setText("Modificar");
        botaoEdit1.setEnabled(false);
        botaoEdit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEdit1ActionPerformed(evt);
            }
        });

        botaoDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001_49.png"))); // NOI18N
        botaoDelete1.setText("Eliminar");
        botaoDelete1.setEnabled(false);
        botaoDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDelete1ActionPerformed(evt);
            }
        });

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Erase.png"))); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        botaprevisualizar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/print.png"))); // NOI18N
        botaprevisualizar1.setText("Imprimir");
        botaprevisualizar1.setEnabled(false);
        botaprevisualizar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaprevisualizar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEdit1, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaprevisualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 653, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botaprevisualizar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2)
                        .addComponent(botaoEdit1)
                        .addComponent(botaoDelete1))))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1346, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 443, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Lista de Formandos Comunidade", jPanel2);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadeformandolocalidade1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Sexo", "Idade", "E.Civil", "Comunidade", "Nr Agregado", "H.Literarias", "Contacto", "A.Actvidade", "N.Empregado", "Curso"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadeformandolocalidade1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeformandolocalidade1MouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(listadeformandolocalidade1);
        listadeformandolocalidade1.getColumnModel().getColumn(1).setHeaderValue("Sexo");
        listadeformandolocalidade1.getColumnModel().getColumn(3).setHeaderValue("E.Civil");
        listadeformandolocalidade1.getColumnModel().getColumn(5).setHeaderValue("Nr Agregado");
        listadeformandolocalidade1.getColumnModel().getColumn(8).setHeaderValue("A.Actvidade");
        listadeformandolocalidade1.getColumnModel().getColumn(9).setHeaderValue("N.Empregado");
        listadeformandolocalidade1.getColumnModel().getColumn(10).setResizable(false);
        listadeformandolocalidade1.getColumnModel().getColumn(10).setHeaderValue("Curso");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel23.setBackground(new java.awt.Color(0, 153, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel24.setBackground(new java.awt.Color(0, 153, 255));

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/print.png"))); // NOI18N
        jButton7.setText("Imprimir");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 843, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel24Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addComponent(jButton7))
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 35, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(97, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(102, 204, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ComboBoxpesquisadistrito2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisadistrito2ItemStateChanged(evt);
            }
        });

        jLabel8.setText("Distrito:");

        jLabel9.setText("Comunidade:");

        ComboBoxpesquisalocalidade2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisalocalidade2ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxpesquisadistrito2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(ComboBoxpesquisalocalidade2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxpesquisadistrito2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisalocalidade2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Lista de Formandos", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1351, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 2, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaNomeCaretUpdate
      //  listarFormando();
    }//GEN-LAST:event_txtPesquisaNomeCaretUpdate

    private void ComboBoxpesquisalocalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisalocalidadeItemStateChanged
        listarCursosLocalidade();
    }//GEN-LAST:event_ComboBoxpesquisalocalidadeItemStateChanged

    private void listadecursoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadecursoMouseClicked

        int selecionado = listadecurso.getSelectedRow();
        int idEmp = Integer.valueOf(listadecurso.getValueAt(selecionado, 0).toString());

        curso = new CursoJpaController().findCurso(idEmp);
        botaoDelete.setEnabled(true);
        botaoEdit.setEnabled(true);
        botaprevisualizar.setEnabled(true);
        // JOptionPane.showMessageDialog(null, emp.getIdformando());


    }//GEN-LAST:event_listadecursoMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CadastroCursoFormacao(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditActionPerformed
        new ModificarCursos(curso).setVisible(true);
        // new ModificarCandidato(emp).setVisible(true);
    }//GEN-LAST:event_botaoEditActionPerformed

    private void botaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteActionPerformed
//          String msg = "Selecciona o Formando primeiro?";
//        int resp = JOptionPane.showOptionDialog(getContentPane(), msg, "confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Não"}, "Não");
//        if (resp == JOptionPane.YES_OPTION){

        eliminarCandidato();
        listarCursos();

//        }
    }//GEN-LAST:event_botaoDeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GerirCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_formAncestorAdded

    private void botaprevisualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaprevisualizarActionPerformed
      
    }//GEN-LAST:event_botaprevisualizarActionPerformed

    private void jTabbedPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseReleased
//        if (jTabbedPane1.getSelectedIndex() == 2) {
//            try {
//                prenchercomboDistrito1();
//            } catch (SQLException ex) {
//                Logger.getLogger(GerirCurso.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            try {
//                prenchercomboLocalidade1();
//            } catch (SQLException ex) {
//                Logger.getLogger(GerirCurso.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            listarRelatorioFormandos();
//        }
//////        else 
//////        if (jTabbedPane1.getSelectedIndex() == 3) {
//////            try {
//////                prenchercomboArea();
//////            } catch (SQLException ex) {
//////                Logger.getLogger(GerirFormando.class.getName()).log(Level.SEVERE, null, ex);
//////            }
//////        }
    }//GEN-LAST:event_jTabbedPane1MouseReleased

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void ComboBoxpesquisadistrito2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisadistrito2ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxpesquisadistrito2ItemStateChanged

    private void ComboBoxpesquisalocalidade2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisalocalidade2ItemStateChanged
      
    }//GEN-LAST:event_ComboBoxpesquisalocalidade2ItemStateChanged

    private void listadeformandolocalidade1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeformandolocalidade1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeformandolocalidade1MouseClicked

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
         List<Formando> formandos = new FormandoJpaController().getRelatorioFormando(ComboBoxpesquisalocalidade2.getSelectedIndex()+1);
         JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(formandos);
        // String path = "/relatorios/recibov.jasper";
         JasperPrint jpPrint = null;
         JasperViewer jv;
         Map par = new HashMap<>();
        // par.put("tf", total);

       // String path = "C:\\Users\\MASSINGUE\\Documents\\NetBeansProjects\\TREE\\src\\Relatorio\\ListadeFormando.jasper";
         String path2=new File("Icone/logoKOIKA.png").getAbsolutePath();
         par.put("img", path2);
         String path = new File("Relatorio/ListadeFormando.jasper").getAbsolutePath();
        try {
            jpPrint = JasperFillManager.fillReport(path, par, ds);//new metodos.ControllerAcess().conetion());
        } catch (JRException ex) {
            Logger.getLogger(GerirCurso.class.getName()).log(Level.SEVERE, null, ex);
        }
        jv = new JasperViewer(jpPrint, false); //O false eh para nao fechar a aplicacao
        JDialog viewer = new JDialog(new javax.swing.JFrame(), "Lista de Formandos", true);
        viewer.setSize(1024, 768);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void txtPesquisaNome1CaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaNome1CaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPesquisaNome1CaretUpdate

    private void ComboBoxpesquisalocalidade3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisalocalidade3ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxpesquisalocalidade3ItemStateChanged

    private void listadecurso1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadecurso1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadecurso1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void botaoEdit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEdit1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoEdit1ActionPerformed

    private void botaoDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDelete1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoDelete1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void botaprevisualizar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaprevisualizar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaprevisualizar1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxpesquisadistrito2;
    private javax.swing.JComboBox ComboBoxpesquisalocalidade;
    private javax.swing.JComboBox ComboBoxpesquisalocalidade2;
    private javax.swing.JComboBox ComboBoxpesquisalocalidade3;
    private javax.swing.JButton botaoDelete;
    private javax.swing.JButton botaoDelete1;
    private javax.swing.JButton botaoEdit;
    private javax.swing.JButton botaoEdit1;
    private javax.swing.JButton botaprevisualizar;
    private javax.swing.JButton botaprevisualizar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listadecurso;
    private javax.swing.JTable listadecurso1;
    private javax.swing.JTable listadeformandolocalidade1;
    private javax.swing.JTextField txtPesquisaNome;
    private javax.swing.JTextField txtPesquisaNome1;
    // End of variables declaration//GEN-END:variables

//    private void prenchercomboDistrito() throws SQLException {
//
//        List<Distrito> distritos = new DistritoDao().mostrarDistritos();
//        ComboBoxpesquisadistrito.removeAllItems();
//        for (Distrito d : distritos) {
//            ComboBoxpesquisadistrito.addItem(d);
//        }
//
//
//
//    }
    
    
    private void prenchercomboDistrito2() throws SQLException {

        List<Distrito> distritos = new DistritoDao().mostrarDistritos();
        ComboBoxpesquisadistrito2.removeAllItems();
        for (Distrito d : distritos) {
            ComboBoxpesquisadistrito2.addItem(d);
        }
    }
//      private void prenchercomboDistrito7() throws SQLException {
//
//        List<Distrito> distritos = new DistritoDao().mostrarDistritos();
//        ComboBoxpesquisadistrito7.removeAllItems();
//        for (Distrito d : distritos) {
//            ComboBoxpesquisadistrito7.addItem(d);
//        }
//
//
//
//    }
//    private void prenchercomboDistrito6() throws SQLException {
//
//        List<Distrito> distritos = new DistritoDao().mostrarDistritos();
//        ComboBoxpesquisadistrito6.removeAllItems();
//        for (Distrito d : distritos) {
//            ComboBoxpesquisadistrito6.addItem(d);
//        }
//
//
//
//    }
    
//     private void prenchercomboLocalidades6() throws SQLException {
//
//        List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
//        ComboBoxpesquisalocalidade6.removeAllItems();
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade6.addItem(p);
//        }
//
//
//
//    }
//      private void prenchercomboLocalidades7() throws SQLException {
//
//        List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
//        ComboBoxpesquisalocalidade7.removeAllItems();
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade7.addItem(p);
//        }
//
//
//
//    }
    

//      private void prenchercomboPosto() throws SQLException {
//       
//             List<Posto> distritos = new PostoDao().mostrarPosto(ComboBoxpesquisadistrito.getSelectedIndex()+1);
//                ComboBoxpesquisaposto.removeAllItems();
//                for (Posto p : distritos) {
//                         ComboBoxpesquisaposto.addItem(p.getPosto());
//               }
//               
//                   
//       
//    }
    private void prenchercomboLocalidades() throws SQLException {

        List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
        ComboBoxpesquisalocalidade.removeAllItems();
        for (Localidade p : comunidades) {
            ComboBoxpesquisalocalidade.addItem(p);
        }



    }
    
//    private void prenchercomboLocalidade1() throws SQLException {
//        List<Localidade> comunidades = new ArrayList<Localidade>();
//        if (ComboBoxpesquisadistrito1.getSelectedIndex() != 0) {
//            comunidades = new LocalidadeJpaController().findLocalidadeEntities();
//        }
//        ComboBoxpesquisalocalidade1.removeAllItems();
//        //ComboBoxpesquisalocalidade1.addItem("--Localidade--");
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade1.addItem(p);
//        }
//    }
    
//     private void prenchercomboLocalidade2() throws SQLException {
//        List<Localidade> comunidades = new ArrayList<Localidade>();
//        if (ComboBoxpesquisadistrito2.getSelectedIndex() != 0) {
//            comunidades = new LocalidadeJpaController().findLocalidadeEntities();
//        }
//        ComboBoxpesquisalocalidade2.removeAllItems();
//        //ComboBoxpesquisalocalidade1.addItem("--Localidade--");
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade2.addItem(p);
//        }
//    }

//    private void prenchercomboLocalidade() throws SQLException {
//
//        List<Localidade> comunidades = new LocalidadeJpaController().getloLocalidades(ComboBoxpesquisadistrito.getSelectedIndex()+1);
//        ComboBoxpesquisalocalidade.removeAllItems();
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade.addItem(p);
//        }
//
//
//
//    }

//    private void prenchercomboLocalidadess() throws SQLException {
//
//        List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
//        ComboBoxpesquisalocalidade1.removeAllItems();
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade1.addItem(p);
//        }
//
//
//
//    }
//    
//    private void prenchercomboDistrito1() throws SQLException {
//
//        List<Distrito> distritos = new DistritoDao().mostrarDistritos();
//        ComboBoxpesquisadistrito1.removeAllItems();
//        ComboBoxpesquisadistrito1.addItem("--Distrito--");
//        for (Distrito d : distritos) {
//            ComboBoxpesquisadistrito1.addItem(d);
//        }
//        if (!distritos.isEmpty()) {
//            ComboBoxpesquisadistrito1.setSelectedIndex(0);
//        }
//
//    }

    public void listarFormando() {
        try {

            List<Formando> formandos = new FormandoDao().listarFormandopesquisado("%" + txtPesquisaNome.getText() + "%");

            DefaultTableModel tbm = (DefaultTableModel) listadecurso.getModel();

            for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
                tbm.removeRow(i);
            }
            int i = 0;
            for (Formando f : formandos) {
                tbm.addRow(new String[1]);

                listadecurso.setValueAt(f.getIdformando(), i, 0);
                listadecurso.setValueAt(f.getNome(), i, 1);
                if (f.getSexo() == true) {
                    listadecurso.setValueAt("Masculino", i, 2);
                } else {
                    listadecurso.setValueAt("Femenino", i, 2);
                }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                listadecurso.setValueAt(f.getIdade(), i, 3);
                listadecurso.setValueAt(f.getIdlocalidade().getLocalidade(), i, 4);
                listadecurso.setValueAt(f.getOutrahabilidades(), i, 5);

                listadecurso.setValueAt(f.getIdcurso().getCurso(), i, 6);


                i++;
            }
        } catch (SQLException ex) {
            Logger.getLogger(GestaoFormando.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    public void listarCursos() {


        List<Cursoformacao> cursos = new CursoformacaoJpaController().findCursoformacaoEntities();

        DefaultTableModel tbm = (DefaultTableModel) listadecurso.getModel();

        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (Cursoformacao c : cursos) {
            tbm.addRow(new String[1]);

            listadecurso.setValueAt(c.getIdcursoformacao(), i, 0);
            listadecurso.setValueAt(c.getCodcurso(), i, 1);
            listadecurso.setValueAt(c.getIdcurso().getCurso(), i, 2);
            listadecurso.setValueAt(c.getIdlocalidade().getLocalidade(), i, 3);
//////            listadecurso.setValueAt(c.getIdmestre().getNome(), i, 4);
            listadecurso.setValueAt(c.getDatainicio(), i, 4);
            listadecurso.setValueAt(c.getDatafim(), i, 5);
            listadecurso.setValueAt(c.getTotalmatriculado(), i, 8);
            listadecurso.setValueAt(c.getMatriculadoH(), i, 6);
            listadecurso.setValueAt(c.getMatriculadoM(), i, 7);
//            listadecurso.setValueAt(c.getDatafim(), i, 5);


            i++;
        }

    }

//    public void listarCursosDistrito() {
//
//
//        List<Formando> formandos = new FormandoJpaController().formandoDistrito(((Distrito) ComboBoxpesquisadistrito.getSelectedItem()).getIddistrito());
//
//        DefaultTableModel tbm = (DefaultTableModel) listadecurso.getModel();
//
//        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
//            tbm.removeRow(i);
//        }
//        int i = 0;
//        for (Formando f : formandos) {
//            tbm.addRow(new String[1]);
//
//            listadecurso.setValueAt(f.getIdformando(), i, 0);
//            listadecurso.setValueAt(f.getNome(), i, 1);
//            if (f.getSexo() == true) {
//                listadecurso.setValueAt("Masculino", i, 2);
//            } else {
//                listadecurso.setValueAt("Feminino", i, 2);
//            }
////                     listadecurso.setValueAt(f.getSexo(), i, 2);
//            listadecurso.setValueAt(f.getIdade(), i, 3);
//            listadecurso.setValueAt(f.getIdlocalidade().getLocalidade(), i, 4);
//            listadecurso.setValueAt(f.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
//            listadecurso.setValueAt(f.getIdcurso().getCurso(), i, 6);
//
//
//            i++;
//        }
//
//
//
//    }

    public void listarCursosLocalidade() {

//            JOptionPane.showMessageDialog(null, closable);
        List<Formando> formandos = new FormandoJpaController().formandoLocalidade(ComboBoxpesquisalocalidade.getSelectedIndex()+1);

        DefaultTableModel tbm = (DefaultTableModel) listadecurso.getModel();

        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (Formando f : formandos) {
            tbm.addRow(new String[1]);

            listadecurso.setValueAt(f.getIdformando(), i, 0);
            listadecurso.setValueAt(f.getNome(), i, 1);
            if (f.getSexo() == true) {
                listadecurso.setValueAt("Masculino", i, 2);
            } else {
                listadecurso.setValueAt("Feminino", i, 2);
            }
//                     listadecurso.setValueAt(f.getSexo(), i, 2);
            listadecurso.setValueAt(f.getIdade(), i, 3);
            listadecurso.setValueAt(f.getIdlocalidade().getLocalidade(), i, 4);
            listadecurso.setValueAt(f.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
            listadecurso.setValueAt(f.getIdcurso().getCurso(), i, 6);


            i++;
        }



    }

//          private void prenchercomboDistrito1() throws SQLException {
//       
//             List<Distrito> distritos = new DistritoDao().mostrarDistritos();
//                ComboBoxpesquisadistrito1.removeAllItems();
//                for (Distrito d : distritos) {
//                         ComboBoxpesquisadistrito1.addItem(d.getDistrito());
//               }
//               
//                   
//       
//    }
//      private void prenchercomboPosto() throws SQLException {
//       
//             List<Posto> distritos = new PostoDao().mostrarPosto(ComboBoxpesquisadistrito.getSelectedIndex()+1);
//                ComboBoxpesquisaposto.removeAllItems();
//                for (Posto p : distritos) {
//                         ComboBoxpesquisaposto.addItem(p.getPosto());
//               }
//               
//                   
//       
//    }
//      
//       private void prenchercomboLocalidade1() throws SQLException {
//       
//             List<Localidade> comunidades = new LocalidadeDao().mostrarLocalidade(ComboBoxpesquisadistrito.getSelectedIndex()+1);
//                ComboBoxpesquisalocalidade1.removeAllItems();
//                for (Localidade p : comunidades) {
//                         ComboBoxpesquisalocalidade1.addItem(p.getLocalidade());
//               }
//               
//                   
//       
//    }
    

    private void eliminarCandidato() {
        String msg = "Deseja Realmente Eliminar O Candidato?";
        int resp = JOptionPane.showOptionDialog(getContentPane(), msg, "confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Não"}, "Não");
        if (resp == JOptionPane.YES_OPTION) {
            try {
                int selecionado = listadecurso.getSelectedRow();
                int nr = 0;
                nr = Integer.valueOf(listadecurso.getValueAt(selecionado, 0).toString());
                Formando f = new FormandoJpaController().findFormando(nr);
                FormandoDao dao = new FormandoDao();
                FormandoJpaController jpa = new FormandoJpaController();
                f.setIdformando(nr);
                dao.destroy(f);
                JOptionPane.showMessageDialog(null, "Formando Eliminado Com Sucesso");
                listarCursos();
            } catch (SQLException ex) {
                Logger.getLogger(GerirCurso.class.getName()).log(Level.SEVERE, null, ex);
            }

        }


    }

 
    
}
