/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dao.DistritoDao;
import Dao.LocalidadeDao;
import Modelo.Distrito;
import Modelo.Formador;
import Modelo.Localidade;
import Modelo.Mestre;
import Modelo.Oficinaequipamento;
import Modelo.OficinaequipamentoPK;
import Modelo.Oficinamestre;
import Persistencia.FormadorJpaController;
import Persistencia.LocalidadeJpaController;
import Persistencia.MestreJpaController;
//import Persistencia.OficinaequipamentoJpaController;
import Persistencia.OficinamestreJpaController;
import Persistencia.exceptions.IllegalOrphanException;
import Persistencia.exceptions.NonexistentEntityException;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MASSINGUE
 */
public class GerirMestres extends javax.swing.JInternalFrame {
     Mestre mestre=new Mestre();
     Oficinaequipamento ofequip=new Oficinaequipamento();
     Oficinaequipamento ofequipa=new Oficinaequipamento();

    /**
     * Creates new form GerirMestres
     */
    public GerirMestres() {
        try {
            initComponents();
            listarFormandores();
            prenchercomboDistrito();
            listarmestrelocalidade();
            prenchercomboDistrito1();
            prenchercomboLocalidade1();
//            prenchercombolocalidade();
        } catch (SQLException ex) {
            Logger.getLogger(GerirMestres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtPesquisaNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ComboBoxpesquisadistrito = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        ComboBoxpesquisalocalidade = new javax.swing.JComboBox();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listadeMestre = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botaoEdit = new javax.swing.JButton();
        botaoDelete = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        ComboBoxpesquisadistrito1 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ComboBoxpesquisalocalidade1 = new javax.swing.JComboBox();
        jPanel12 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadeMestre1 = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        botaoDelete1 = new javax.swing.JButton();

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel9AncestorAdded(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(102, 204, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        txtPesquisaNome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtPesquisaNomeCaretUpdate(evt);
            }
        });

        jLabel2.setText("Pesquisar por Nome:");

        ComboBoxpesquisadistrito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisadistritoItemStateChanged(evt);
            }
        });

        jLabel4.setText("Distrito:");

        jLabel6.setText("Comunidade:");

        ComboBoxpesquisalocalidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisalocalidadeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxpesquisadistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(ComboBoxpesquisalocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(849, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPesquisaNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisadistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisalocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadeMestre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nome Completo", "Sexo", "Idade", "Comunidade", "Distrito", "Sector de Atividade", "Habilitacoes Literarias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadeMestre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeMestreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listadeMestre);
        listadeMestre.getColumnModel().getColumn(0).setMinWidth(70);
        listadeMestre.getColumnModel().getColumn(0).setPreferredWidth(70);
        listadeMestre.getColumnModel().getColumn(0).setMaxWidth(70);
        listadeMestre.getColumnModel().getColumn(1).setMinWidth(250);
        listadeMestre.getColumnModel().getColumn(1).setPreferredWidth(250);
        listadeMestre.getColumnModel().getColumn(1).setMaxWidth(250);
        listadeMestre.getColumnModel().getColumn(2).setMinWidth(100);
        listadeMestre.getColumnModel().getColumn(2).setPreferredWidth(100);
        listadeMestre.getColumnModel().getColumn(2).setMaxWidth(100);
        listadeMestre.getColumnModel().getColumn(3).setMinWidth(70);
        listadeMestre.getColumnModel().getColumn(3).setPreferredWidth(70);
        listadeMestre.getColumnModel().getColumn(3).setMaxWidth(70);
        listadeMestre.getColumnModel().getColumn(4).setMinWidth(150);
        listadeMestre.getColumnModel().getColumn(4).setPreferredWidth(150);
        listadeMestre.getColumnModel().getColumn(4).setMaxWidth(150);
        listadeMestre.getColumnModel().getColumn(5).setMinWidth(150);
        listadeMestre.getColumnModel().getColumn(5).setPreferredWidth(150);
        listadeMestre.getColumnModel().getColumn(5).setMaxWidth(150);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo.png"))); // NOI18N
        jButton1.setText("Novo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        botaoEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001_45.png"))); // NOI18N
        botaoEdit.setText("Modificar");
        botaoEdit.setEnabled(false);
        botaoEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditActionPerformed(evt);
            }
        });

        botaoDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/001_49.png"))); // NOI18N
        botaoDelete.setText("Eliminar");
        botaoDelete.setEnabled(false);
        botaoDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDeleteActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Erase.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(botaoEdit)
                    .addComponent(botaoDelete)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registo de Mestre", jPanel9);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel10AncestorAdded(evt);
            }
        });

        jPanel11.setBackground(new java.awt.Color(102, 204, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ComboBoxpesquisadistrito1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisadistrito1ItemStateChanged(evt);
            }
        });
        ComboBoxpesquisadistrito1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBoxpesquisadistrito1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Distrito:");

        jLabel7.setText("Comunidade:");

        ComboBoxpesquisalocalidade1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisalocalidade1ItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxpesquisadistrito1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(ComboBoxpesquisalocalidade1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxpesquisadistrito1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisalocalidade1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadeMestre1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Numero", "Nome Completo", "Sexo", "Idade", "Comunidade", "Distrito", "Sector de Atividade", "Habilitacoes Literarias"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadeMestre1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeMestre1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listadeMestre1);
        listadeMestre1.getColumnModel().getColumn(0).setMinWidth(70);
        listadeMestre1.getColumnModel().getColumn(0).setPreferredWidth(70);
        listadeMestre1.getColumnModel().getColumn(0).setMaxWidth(70);
        listadeMestre1.getColumnModel().getColumn(1).setMinWidth(250);
        listadeMestre1.getColumnModel().getColumn(1).setPreferredWidth(250);
        listadeMestre1.getColumnModel().getColumn(1).setMaxWidth(250);
        listadeMestre1.getColumnModel().getColumn(2).setMinWidth(100);
        listadeMestre1.getColumnModel().getColumn(2).setPreferredWidth(100);
        listadeMestre1.getColumnModel().getColumn(2).setMaxWidth(100);
        listadeMestre1.getColumnModel().getColumn(3).setMinWidth(70);
        listadeMestre1.getColumnModel().getColumn(3).setPreferredWidth(70);
        listadeMestre1.getColumnModel().getColumn(3).setMaxWidth(70);
        listadeMestre1.getColumnModel().getColumn(4).setMinWidth(150);
        listadeMestre1.getColumnModel().getColumn(4).setPreferredWidth(150);
        listadeMestre1.getColumnModel().getColumn(4).setMaxWidth(150);
        listadeMestre1.getColumnModel().getColumn(5).setMinWidth(150);
        listadeMestre1.getColumnModel().getColumn(5).setPreferredWidth(150);
        listadeMestre1.getColumnModel().getColumn(5).setMaxWidth(150);

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1437, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel13.setBackground(new java.awt.Color(0, 153, 255));
        jPanel13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel14.setBackground(new java.awt.Color(0, 153, 255));

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Erase.png"))); // NOI18N
        jButton5.setText("Cancelar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        botaoDelete1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/print.png"))); // NOI18N
        botaoDelete1.setText("Imprimir");
        botaoDelete1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoDelete1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(botaoDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1117, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(botaoDelete1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(3, 3, 3))))
        );

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1463, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 494, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Lista de Mestre", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 482, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPesquisaNomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtPesquisaNomeCaretUpdate
     listarmestre();
    }//GEN-LAST:event_txtPesquisaNomeCaretUpdate

    private void ComboBoxpesquisadistritoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisadistritoItemStateChanged
        try {
            prenchercomboLocalidade();
            listarmestredistrito()
                  ;
        } catch (SQLException ex) {
            Logger.getLogger(GestaoFormando.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboBoxpesquisadistritoItemStateChanged

    private void ComboBoxpesquisalocalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisalocalidadeItemStateChanged
         listarmestrelocalidade();
    }//GEN-LAST:event_ComboBoxpesquisalocalidadeItemStateChanged

    private void listadeMestreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeMestreMouseClicked

        int selecionado=listadeMestre.getSelectedRow();
        int idEmp=Integer.valueOf(listadeMestre.getValueAt(selecionado, 0).toString());

        mestre=new MestreJpaController().findMestre(idEmp);
        botaoDelete.setEnabled(true);
        botaoEdit.setEnabled(true);
        // botaoprint.setEnabled(true);
        listarequipamentosMestre(idEmp);
//        // JOptionPane.showMessageDialog(null, emp.getIdformando());

    }//GEN-LAST:event_listadeMestreMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        new CadastrarMestre(null, true).setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void botaoEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEditActionPerformed
          new ModificarMestre(mestre).setVisible(true);
    }//GEN-LAST:event_botaoEditActionPerformed

    private void botaoDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDeleteActionPerformed
         String msg = "Deseja Realmente Eliminar O Mestre?";
        int resp = JOptionPane.showOptionDialog(getContentPane(), msg, "confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Não"}, "Não");
        if (resp == JOptionPane.YES_OPTION){
             try {                        
                 int selecionado=listadeMestre.getSelectedRow();
                             int nr=0;
                             nr=Integer.valueOf(listadeMestre.getValueAt(selecionado, 0).toString());
                             new MestreJpaController().destroy(nr);
                             
                             JOptionPane.showMessageDialog(null, "Mestre Eliminado Com Sucesso");
                             listarFormandores();
             } catch (IllegalOrphanException ex) {
                 Logger.getLogger(GerirMestres.class.getName()).log(Level.SEVERE, null, ex);
             } catch (NonexistentEntityException ex) {
                 Logger.getLogger(GerirMestres.class.getName()).log(Level.SEVERE, null, ex);
             }
             
            
             }
    }//GEN-LAST:event_botaoDeleteActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jPanel9AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel9AncestorAdded
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(GerirMestres.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jPanel9AncestorAdded

    private void ComboBoxpesquisadistrito1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisadistrito1ItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_ComboBoxpesquisadistrito1ItemStateChanged

    private void ComboBoxpesquisalocalidade1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisalocalidade1ItemStateChanged
        listarmestrelocalidade1();
    }//GEN-LAST:event_ComboBoxpesquisalocalidade1ItemStateChanged

    private void listadeMestre1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeMestre1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listadeMestre1MouseClicked

    private void botaoDelete1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoDelete1ActionPerformed
      List<Oficinamestre> le = new OficinamestreJpaController().mestrelocalidade(ComboBoxpesquisalocalidade1.getSelectedIndex()+1);
      //  formadores.add(le);
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(le);
        // String path = "/relatorios/recibov.jasper";
        JasperPrint jpPrint = null;
        JasperViewer jv;
        Map par = new HashMap<>();
        // par.put("tf", total);

        // String path = "C:\\Users\\MASSINGUE\\Documents\\NetBeansProjects\\TREE\\src\\Relatorio\\listademestre.jasper";
        String path = new File("Relatorio/listademestre.jasper").getAbsolutePath();
         String path2=new File("Icone/logoKOIKA.png").getAbsolutePath();
         par.put("img", path2);
        try {
            jpPrint = JasperFillManager.fillReport(path,par, ds);//new metodos.ControllerAcess().conetion());
        } catch (JRException ex) {
            Logger.getLogger(GerirFormando.class.getName()).log(Level.SEVERE, null, ex);
        }
        jv = new JasperViewer(jpPrint, false); //O false eh para nao fechar a aplicacao
        JDialog viewer = new JDialog(new javax.swing.JFrame(), "Caracterizacao do Mentor", true);
        viewer.setSize(1024, 768);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);
    }//GEN-LAST:event_botaoDelete1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jPanel10AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel10AncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_jPanel10AncestorAdded

    private void ComboBoxpesquisadistrito1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBoxpesquisadistrito1ActionPerformed
        listarmestredistrito1();
    }//GEN-LAST:event_ComboBoxpesquisadistrito1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxpesquisadistrito;
    private javax.swing.JComboBox ComboBoxpesquisadistrito1;
    private javax.swing.JComboBox ComboBoxpesquisalocalidade;
    private javax.swing.JComboBox ComboBoxpesquisalocalidade1;
    private javax.swing.JButton botaoDelete;
    private javax.swing.JButton botaoDelete1;
    private javax.swing.JButton botaoEdit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listadeMestre;
    private javax.swing.JTable listadeMestre1;
    private javax.swing.JTextField txtPesquisaNome;
    // End of variables declaration//GEN-END:variables
//     private void prenchercomboDistrito() throws SQLException {
//    List<Distrito> distritos = new DistritoDao().mostrarDistritos();
//        ComboBoxpesquisadistrito.removeAllItems();
//        ComboBoxpesquisadistrito.addItem("--Distrito--");
//        for (Distrito d : distritos) {
//            ComboBoxpesquisadistrito.addItem(d);
//        }
//        if (!distritos.isEmpty()) {
//            ComboBoxpesquisadistrito.setSelectedIndex(0);
//        }
//
//    }
      private void prenchercomboDistrito() throws SQLException {
       
             List<Distrito> distritos = new DistritoDao().mostrarDistritos();
                ComboBoxpesquisadistrito.removeAllItems();
                for (Distrito d : distritos) {
                         ComboBoxpesquisadistrito.addItem(d);
               }
               
                   
       
    }

//    private void prenchercomboLocalidade() throws SQLException {
//        List<Localidade> comunidades = new ArrayList<Localidade>();
//        if (ComboBoxpesquisadistrito.getSelectedIndex() != 0) {
//            comunidades = new LocalidadeDao().mostrarLocalidade(((Distrito) ComboBoxpesquisadistrito.getSelectedItem()).getIddistrito());
//        }
//        ComboBoxpesquisalocalidade.removeAllItems();
//        ComboBoxpesquisalocalidade.addItem("--Localidade--");
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade.addItem(p);
//        }
//    }
       private void prenchercomboLocalidade() throws SQLException {
       
             List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
                ComboBoxpesquisalocalidade.removeAllItems();
                for (Localidade p : comunidades) {
                         ComboBoxpesquisalocalidade.addItem(p);
               }
               
                   
       
    }
       
        private void prenchercomboDistrito1() throws SQLException {
       
             List<Distrito> distritos = new DistritoDao().mostrarDistritos();
                ComboBoxpesquisadistrito1.removeAllItems();
                for (Distrito d : distritos) {
                         ComboBoxpesquisadistrito1.addItem(d.getDistrito());
               }
               
                   
       
    }

//    private void prenchercomboLocalidade() throws SQLException {
//        List<Localidade> comunidades = new ArrayList<Localidade>();
//        if (ComboBoxpesquisadistrito.getSelectedIndex() != 0) {
//            comunidades = new LocalidadeDao().mostrarLocalidade(((Distrito) ComboBoxpesquisadistrito.getSelectedItem()).getIddistrito());
//        }
//        ComboBoxpesquisalocalidade.removeAllItems();
//        ComboBoxpesquisalocalidade.addItem("--Localidade--");
//        for (Localidade p : comunidades) {
//            ComboBoxpesquisalocalidade.addItem(p);
//        }
//    }
       private void prenchercomboLocalidade1() throws SQLException {
       
             List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
                ComboBoxpesquisalocalidade1.removeAllItems();
                for (Localidade p : comunidades) {
                         ComboBoxpesquisalocalidade1.addItem(p);
               }
               
                   
       
    }
       
       

    public void listarFormandores() {
                     
           
            List<Mestre> mestres =new MestreJpaController().findMestreEntities();
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre.setValueAt(m.getIdade(), i, 3);
                    listadeMestre.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    } 
     public void listarmestrelocalidade1() {
                     
            int idlocalidade=0;
            idlocalidade=ComboBoxpesquisalocalidade1.getSelectedIndex()+1;

            List<Mestre> mestres =new MestreJpaController().mestrelocalidade(idlocalidade);
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre1.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre1.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre1.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre1.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre1.setValueAt(m.getIdade(), i, 3);
                    listadeMestre1.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre1.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre1.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre1.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    } 
    
     public void listarmestredistrito1() {
                     
            int idlocalidade=0;
            idlocalidade=ComboBoxpesquisadistrito1.getSelectedIndex()+1;

            List<Mestre> mestres =new MestreJpaController().mestrelocalidade(idlocalidade);
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre1.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre1.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre1.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre1.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre1.setValueAt(m.getIdade(), i, 3);
                    listadeMestre1.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre1.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre1.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre1.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    } 
    
    
    
     public void listarmestre() {
                     
           
            List<Mestre> mestres =new MestreJpaController().getmestre("%"+txtPesquisaNome.getText()+"%");
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre.setValueAt(m.getIdade(), i, 3);
                    listadeMestre.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    }  
      public void listarmestredistrito() {
                     
//           int iddistrito=0;
          // Distrito d=;
            List<Mestre> mestres =new MestreJpaController().mestreDistrito(ComboBoxpesquisadistrito.getSelectedIndex()+1);
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre.setValueAt(m.getIdade(), i, 3);
                    listadeMestre.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    }  
     
     public void listarmestrelocalidade() {
                     
            int idlocalidade=0;
            idlocalidade=ComboBoxpesquisalocalidade.getSelectedIndex()+1;
//            JOptionPane.showMessageDialog(null, idlocalidade);
//            idlocalidade=l.getIdlocalidade();
            List<Mestre> mestres =new MestreJpaController().mestrelocalidade(idlocalidade);
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre.setValueAt(m.getIdade(), i, 3);
                    listadeMestre.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    } 
     
      public void listarEquipamentosMestre() {
                     
            int idlocalidade=0;
            idlocalidade=ComboBoxpesquisalocalidade.getSelectedIndex()+1;
//            JOptionPane.showMessageDialog(null, idlocalidade);
//            idlocalidade=l.getIdlocalidade();
            List<Mestre> mestres =new MestreJpaController().mestrelocalidade(idlocalidade);
           
                DefaultTableModel tbm=(DefaultTableModel) listadeMestre.getModel();
                
                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
                    tbm.removeRow(i);
                }
                int i=0;
                for (Mestre m  : mestres) {
                    tbm.addRow(new String[1]);
                    
                    listadeMestre.setValueAt(m.getIdmestre(), i, 0);
                    listadeMestre.setValueAt(m.getNome(), i, 1);
                    if(m.getSexo()==true){
                        listadeMestre.setValueAt("Masculino", i, 2);}
                    else{
                       listadeMestre.setValueAt("Femenino", i, 2);
                    }
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
                    listadeMestre.setValueAt(m.getIdade(), i, 3);
                    listadeMestre.setValueAt(m.getIdlocalidade().getLocalidade(), i, 4);
                    listadeMestre.setValueAt(m.getIdlocalidade().getIdposto().getIddistrito().getDistrito(), i, 5);
                    
                    listadeMestre.setValueAt(m.getIdcurso().getCurso(), i, 6);
                    listadeMestre.setValueAt(m.getIdnivelhabilitacao().getNivelhabilitacao(), i, 7);
                    
                    
                    i++;
        }
       
    }   
     
     public void listarequipamentosMestre(int m) {
                     
           
//            List<Oficinaequipamento>  equip = new OficinaequipamentoJpaController().getequipamentosmestre(m);
//           
//                DefaultTableModel tbm=(DefaultTableModel) listadeEquipamentoOficina.getModel();
//                
//                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
//                    tbm.removeRow(i);
//                }
//                int i=0;
//                for(Oficinaequipamento e : equip){
//                    tbm.addRow(new String[1]);
//                    
//                    listadeEquipamentoOficina.setValueAt(e.getOficinamestre().getIdmestre(), i, 0);
//                    listadeEquipamentoOficina.setValueAt(e.getOficinamestre().getMestre().getNome(), i, 1);
//                    listadeEquipamentoOficina.setValueAt(e.getEquipamento().getIdequipamento(), i, 2);
//                    listadeEquipamentoOficina.setValueAt(e.getEquipamento().getEquipamento(), i, 3);
//                    listadeEquipamentoOficina.setValueAt(e.getQuantidade(), i, 4);
//                    
//                    i++;
//        }
       
    }   
//   public void listarequipamentoMestre(int m) {
                     
           
//            List<Oficinaequipamento>  equip = new OficinaequipamentoJpaController().getequipamentosmestre(m);
//           
//                DefaultTableModel tbm=(DefaultTableModel) listadeEquipamentoOficina.getModel();
//                
//                for (int i = tbm.getRowCount()-1; i >= 0; i--) {
//                    tbm.removeRow(i);
//                }
//                int i=0;
//                for(Oficinaequipamento e : equip){
//                    tbm.addRow(new String[1]);
//                    
//                    listadeEquipamentoOficina.setValueAt(e.getOficinamestre().getIdmestre(), i, 0);
//                    listadeEquipamentoOficina.setValueAt(e.getOficinamestre().getMestre().getNome(), i, 1);
//                    listadeEquipamentoOficina.setValueAt(e.getEquipamento().getIdequipamento(), i, 2);
//                    listadeEquipamentoOficina.setValueAt(e.getEquipamento().getEquipamento(), i, 3);
//                    listadeEquipamentoOficina.setValueAt(e.getQuantidade(), i, 4);
//                    
//                    i++;
//        }
//       
//    }     
}
