/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dao.CursoDao;
import Dao.DistritoDao;
import Modelo.Artigo;
import Modelo.Curso;
import Modelo.Distrito;
import Modelo.Formacaoturma;
import Modelo.Formador;
import Modelo.Formando;
import Modelo.Localidade;
import Modelo.Mes;
import Modelo.Mestre;
import Modelo.Produtos;
import Persistencia.ArtigoJpaController;
import Persistencia.FormacaoturmaJpaController;
import Persistencia.FormadorJpaController;
import Persistencia.FormandoJpaController;
import Persistencia.LocalidadeJpaController;
import Persistencia.MesJpaController;
import Persistencia.MestreJpaController;
import Persistencia.ProdutosJpaController;
import Persistencia.exceptions.IllegalOrphanException;
import Persistencia.exceptions.PreexistingEntityException;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.Date;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MASSINGUE
 */
public class ModificarTurma extends javax.swing.JDialog {
 Formacaoturma formando = new Formacaoturma();
 Formacaoturma formturm = new Formacaoturma();
 int idEmp=0;
    /**
     * Creates new form CadastroTurma
     */
    public ModificarTurma(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            initComponents();
            prenchercomboDistrito();
            prenchercomboLocalidade();
            prenchercombocurso();
            prencherFormador();
            reprovado.setSelected(true);
            naodesistente.setSelected(true);
            dfim.setDateFormatString("dd/MM/yyyy");
            dinicio.setDateFormatString("dd/MM/yyyy");
            dinicio.setDate(new java.util.Date());
            dfim.setDate(new java.util.Date());
             Dimension centro=Toolkit.getDefaultToolkit().getScreenSize();
             this.setLocation((centro.width-getWidth())/2 ,(centro.height-getHeight())/2);
        } catch (SQLException ex) {
            Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    ModificarTurma(Formacaoturma formando) {
     try {
         this.formando=formando;
         initComponents();
         prenchercomboDistrito();
         prenchercomboLocalidade();
         prenchercombocurso();
         prenchercombomes();
         prencherFormador();
         prencherproducao();
         reprovado.setSelected(true);
         naodesistente.setSelected(true);
         dfim.setDateFormatString("dd/MM/yyyy");
         dinicio.setDateFormatString("dd/MM/yyyy");
         dinicio.setDate(new java.util.Date());
         dfim.setDate(new java.util.Date());
         prenchercampos();
         Dimension centro=Toolkit.getDefaultToolkit().getScreenSize();
         this.setLocation((centro.width-getWidth())/2 ,(centro.height-getHeight())/2);
     } catch (SQLException ex) {
         Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
     }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        botaoguardar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtnome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        txtSexo = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        txtIdade = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txtEstadoCivil = new javax.swing.JTextField();
        txtHabilitacoes = new javax.swing.JTextField();
        jPanel21 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        comboformador = new javax.swing.JComboBox();
        combomestre = new javax.swing.JComboBox();
        dinicio = new com.toedter.calendar.JDateChooser();
        dfim = new com.toedter.calendar.JDateChooser();
        jPanel19 = new javax.swing.JPanel();
        aprovado = new javax.swing.JRadioButton();
        reprovado = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jPanel20 = new javax.swing.JPanel();
        desistente = new javax.swing.JRadioButton();
        naodesistente = new javax.swing.JRadioButton();
        jLabel13 = new javax.swing.JLabel();
        txtclassificacao = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listadeprodutos = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtquantidade = new javax.swing.JTextField();
        comboproduto = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        combomes = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanel17 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        txthorasfreq1 = new javax.swing.JTextField();
        txthorasfalta1 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        txtocorrencias = new javax.swing.JTextField();
        txthorasfreq2 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txthorasfreq3 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        txthorasfalta2 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txthorasfalta3 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listaformando = new javax.swing.JTable();
        jPanel10 = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        comboDistrito = new javax.swing.JComboBox();
        ComboLocalidade = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel55 = new javax.swing.JLabel();
        combocurso = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel7.setBackground(new java.awt.Color(0, 153, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBackground(new java.awt.Color(0, 153, 255));

        botaoguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/save1.png"))); // NOI18N
        botaoguardar.setText("Guardar");
        botaoguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoguardarActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Erase.png"))); // NOI18N
        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(botaoguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 484, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botaoguardar)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome Completo:");

        txtnome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnomeKeyPressed(evt);
            }
        });

        jLabel5.setText("Habilitacoes Literarias:");

        jLabel24.setText("Idade:");

        jLabel14.setText("Sexo:");

        jLabel34.setText("Estado Civil:");

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtHabilitacoes, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
                            .addComponent(txtnome)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel34)
                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel14)))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel34)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHabilitacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel21.setBackground(new java.awt.Color(255, 255, 255));
        jPanel21.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel18.setText("Nome Formador:");

        jLabel19.setText("Data Inicio:");

        jLabel20.setText("Nome do Mestre:");

        jLabel23.setText("Data fim:");

        jPanel19.setBackground(new java.awt.Color(255, 255, 255));
        jPanel19.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup1.add(aprovado);
        aprovado.setText("Aprovado");

        buttonGroup1.add(reprovado);
        reprovado.setText("Reprovado");

        jLabel12.setText("Aprovação:");

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel19Layout.createSequentialGroup()
                        .addComponent(aprovado)
                        .addGap(18, 18, 18)
                        .addComponent(reprovado))
                    .addComponent(jLabel12))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aprovado)
                    .addComponent(reprovado))
                .addContainerGap())
        );

        jPanel20.setBackground(new java.awt.Color(255, 255, 255));
        jPanel20.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        buttonGroup2.add(desistente);
        desistente.setText("Sim");

        buttonGroup2.add(naodesistente);
        naodesistente.setText("Não");

        jLabel13.setText("Desistencia:");

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel20Layout.createSequentialGroup()
                        .addComponent(desistente)
                        .addGap(18, 18, 18)
                        .addComponent(naodesistente))
                    .addComponent(jLabel13))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(desistente)
                    .addComponent(naodesistente))
                .addContainerGap())
        );

        jLabel31.setText("Classificação:");

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dinicio, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                    .addComponent(jLabel18)
                    .addComponent(jLabel19)
                    .addComponent(comboformador, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(39, 39, 39)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(dfim, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(combomestre, javax.swing.GroupLayout.Alignment.LEADING, 0, 173, Short.MAX_VALUE))
                    .addComponent(jLabel23))
                .addGap(48, 48, 48)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addGap(0, 60, Short.MAX_VALUE))
                    .addComponent(txtclassificacao))
                .addContainerGap())
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel21Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jLabel20))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboformador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(combomestre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtclassificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel23))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(dinicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dfim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel21Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel21, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Dados dos Formandos Turma", jPanel9);

        jPanel15.setBackground(new java.awt.Color(255, 255, 255));
        jPanel15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadeprodutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Produto", "Quantidade", "Periodo"
            }
        ));
        jScrollPane2.setViewportView(listadeprodutos);
        listadeprodutos.getColumnModel().getColumn(0).setMinWidth(50);
        listadeprodutos.getColumnModel().getColumn(0).setPreferredWidth(50);
        listadeprodutos.getColumnModel().getColumn(0).setMaxWidth(50);
        listadeprodutos.getColumnModel().getColumn(2).setMinWidth(70);
        listadeprodutos.getColumnModel().getColumn(2).setPreferredWidth(70);
        listadeprodutos.getColumnModel().getColumn(2).setMaxWidth(70);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
        );

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel7.setText("Produto:");

        jLabel8.setText("Quantidade:");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Go forward.png"))); // NOI18N
        jButton1.setEnabled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Periodo:");

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtquantidade)
                    .addComponent(comboproduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 217, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(combomes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboproduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtquantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(combomes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Quantidades produzidas", jPanel15);

        jPanel14.setBackground(new java.awt.Color(255, 255, 255));
        jPanel14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel17.setBackground(new java.awt.Color(255, 255, 255));
        jPanel17.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 53, Short.MAX_VALUE)
        );

        jPanel22.setBackground(new java.awt.Color(255, 255, 255));
        jPanel22.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setText("Nº de horas de form freq no mês 1º:");

        txthorasfreq1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txthorasfreq1KeyPressed(evt);
            }
        });

        jLabel30.setText("Nº de horas em falta no mês 1º:");

        jLabel32.setText("Ocorrencias:");

        jLabel35.setText("Nº de horas de form freq no mês 2º:");

        jLabel36.setText("Nº de horas de form freq no mês 3º:");

        jLabel37.setText("Nº de horas em falta no mês 2º:");

        jLabel38.setText("Nº de horas em falta no mês 3º:");

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txthorasfalta2, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel37, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txthorasfreq1, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txthorasfreq2)
                                .addComponent(txthorasfreq3))
                            .addComponent(jLabel36))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel30)
                            .addComponent(txthorasfalta1)
                            .addComponent(txthorasfalta3, javax.swing.GroupLayout.DEFAULT_SIZE, 165, Short.MAX_VALUE)
                            .addComponent(jLabel38, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(49, 49, 49)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel32)
                    .addComponent(txtocorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(jLabel30))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txthorasfreq1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txthorasfalta1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel32)
                        .addGroup(jPanel22Layout.createSequentialGroup()
                            .addGap(20, 20, 20)
                            .addComponent(txtocorrencias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(28, 28, 28)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel35)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthorasfreq2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel37)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthorasfalta2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(19, 19, 19)
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthorasfreq3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txthorasfalta3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel22, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel14Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Inicio das actividades", jPanel14);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listaformando.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Numero", "Nome"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listaformando.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listaformandoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listaformando);
        listaformando.getColumnModel().getColumn(0).setResizable(false);
        listaformando.getColumnModel().getColumn(0).setPreferredWidth(3);
        listaformando.getColumnModel().getColumn(1).setMinWidth(200);
        listaformando.getColumnModel().getColumn(1).setPreferredWidth(200);
        listaformando.getColumnModel().getColumn(1).setMaxWidth(200);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel10.setBackground(new java.awt.Color(0, 153, 255));
        jPanel10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel25.setText("Distrito:");

        comboDistrito.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboDistritoItemStateChanged(evt);
            }
        });

        ComboLocalidade.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboLocalidadeItemStateChanged(evt);
            }
        });

        jLabel33.setText("Comunidade:");

        jLabel55.setText("Area de Formacao:");

        combocurso.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combocursoItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel55)
                    .addComponent(combocurso, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel25)
                    .addComponent(comboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addComponent(jLabel55)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(combocurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel25)
                            .addComponent(jLabel33))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(comboDistrito, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ComboLocalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTabbedPane1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoguardarActionPerformed
        String msg = "Deseja Realmente Modificar O Formador?";
        int resp = JOptionPane.showOptionDialog(getContentPane(), msg, "confirmação", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Sim", "Não"}, "Não");
        if (resp == JOptionPane.YES_OPTION){
      
        verificarcampos();
        }
         

    }//GEN-LAST:event_botaoguardarActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void comboDistritoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboDistritoItemStateChanged
        //        try {
            //            prenchercomboLocalidade();
            //        } catch (SQLException ex) {
            //            Logger.getLogger(CadastrarFormando.class.getName()).log(Level.SEVERE, null, ex);
            //        }
    }//GEN-LAST:event_comboDistritoItemStateChanged

    private void txtnomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnomeKeyPressed
        //  botaoguardar.setEnabled(botaAceitar());
    }//GEN-LAST:event_txtnomeKeyPressed

    private void ComboLocalidadeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboLocalidadeItemStateChanged
     try {
         listarFormando();
         prencherFormador();
         prencherMestre();
     } catch (SQLException ex) {
         Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_ComboLocalidadeItemStateChanged

    private void combocursoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combocursoItemStateChanged
     try {
         listarFormando();
         prencherproduto();
     } catch (SQLException ex) {
         Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
     }
    }//GEN-LAST:event_combocursoItemStateChanged

    private void listaformandoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listaformandoMouseClicked
//        int selecionado = listaformando.getSelectedRow();
//       // int idEmpr = Integer.valueOf(listaformando.getValueAt(selecionado, 0).toString());
//        idEmp=Integer.valueOf(listaformando.getValueAt(selecionado, 0).toString());
//
//        formando = new FormandoJpaController().findFormando(idEmp);
//        txtnome.setText(formando.getNome());
//        txtIdade.setText(String.valueOf(formando.getIdade()));
//        txtEstadoCivil.setText(formando.getIdestadocivil().getEstado());
//        txtHabilitacoes.setText(formando.getIdnivelhabilitacao().getNivelhabilitacao());
//         if (formando.getSexo()==true) 
//                     txtSexo.setText("Masculino");
//                     
//                 else 
//                 
//                     txtSexo.setText("Feminino");
    }//GEN-LAST:event_listaformandoMouseClicked

    private void txthorasfreq1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txthorasfreq1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txthorasfreq1KeyPressed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        adicionarprodutos();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarTurma.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ModificarTurma dialog = new ModificarTurma(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboLocalidade;
    private javax.swing.JRadioButton aprovado;
    private javax.swing.JButton botaoguardar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox comboDistrito;
    private javax.swing.JComboBox combocurso;
    private javax.swing.JComboBox comboformador;
    private javax.swing.JComboBox combomes;
    private javax.swing.JComboBox combomestre;
    private javax.swing.JComboBox comboproduto;
    private javax.swing.JRadioButton desistente;
    private com.toedter.calendar.JDateChooser dfim;
    private com.toedter.calendar.JDateChooser dinicio;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listadeprodutos;
    private javax.swing.JTable listaformando;
    private javax.swing.JRadioButton naodesistente;
    private javax.swing.JRadioButton reprovado;
    private javax.swing.JTextField txtEstadoCivil;
    private javax.swing.JTextField txtHabilitacoes;
    private javax.swing.JTextField txtIdade;
    private javax.swing.JTextField txtSexo;
    private javax.swing.JTextField txtclassificacao;
    private javax.swing.JTextField txthorasfalta1;
    private javax.swing.JTextField txthorasfalta2;
    private javax.swing.JTextField txthorasfalta3;
    private javax.swing.JTextField txthorasfreq1;
    private javax.swing.JTextField txthorasfreq2;
    private javax.swing.JTextField txthorasfreq3;
    private javax.swing.JTextField txtnome;
    private javax.swing.JTextField txtocorrencias;
    private javax.swing.JTextField txtquantidade;
    // End of variables declaration//GEN-END:variables

    private void prenchercombocurso() throws SQLException {
       
             List<Curso> es = new CursoDao().prencherCurso();
                combocurso.removeAllItems();
                for ( Curso d : es) {
                        combocurso.addItem(d);
               }
    }
     private void prenchercombomes() throws SQLException {
       
             List<Mes> es = new MesJpaController().findMesEntities();
                combomes.removeAllItems();
                for ( Mes d : es) {
                        combomes.addItem(d);
               }
    }
    private void prencherproduto() throws SQLException {
       
             List<Produtos> es = new ProdutosJpaController().getcurso(combocurso.getSelectedIndex()+1);
                comboproduto.removeAllItems();
                for ( Produtos d : es) {
                        comboproduto.addItem(d);
               }
    }
    private void prenchercomboDistrito() throws SQLException {
       
             List<Distrito> distritos = new DistritoDao().mostrarDistritos();
                comboDistrito.removeAllItems();
                for (Distrito d : distritos) {
                         comboDistrito.addItem(d);
               } 
    }
     
       private void prenchercomboLocalidade() throws SQLException {
       
             List<Localidade> comunidades = new LocalidadeJpaController().findLocalidadeEntities();
                ComboLocalidade.removeAllItems();
                for (Localidade p : comunidades) {
                         ComboLocalidade.addItem(p);
               } 
    }
         private void prencherFormador() throws SQLException {
       
             List<Formador> es = new FormadorJpaController().formadorLocalidade(ComboLocalidade.getSelectedIndex()+1);
                comboformador.removeAllItems();
                for ( Formador d : es) {
                        comboformador.addItem(d);
               }
           
    }
          private void prencherMestre() throws SQLException {
       
             List<Mestre> es = new MestreJpaController().mestrelocalidade(ComboLocalidade.getSelectedIndex()+1);
                combomestre.removeAllItems();
                for (Mestre d : es) {
                        combomestre.addItem(d);
               }
           
    }
         
       public void listarFormando(){
  
//        
//        int curso = ((Curso)combocurso.getSelectedItem()).getIdcurso();
        List<Formando> formandos = new FormandoJpaController().getprio1(ComboLocalidade.getSelectedIndex()+1, combocurso.getSelectedIndex()+1);

        DefaultTableModel tbm = (DefaultTableModel) listaformando.getModel();

        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (Formando f : formandos) {
            tbm.addRow(new String[1]);
 
            listaformando.setValueAt(f.getIdformando(), i, 0);
            listaformando.setValueAt(f.getNome(), i, 1);
               


            i++;
        }
     
     }
       private void adicionarprodutos(){
         int idproduto=(((Produtos)comboproduto.getSelectedItem()).getIdproduto());
         String produto=(((Produtos)comboproduto.getSelectedItem()).getProduto());
         int idmes=(((Mes)combomes.getSelectedItem()).getIdmes());
         String mes=(((Mes)combomes.getSelectedItem()).getMes());

        double qtd=Double.valueOf(txtquantidade.getText());
       
        DefaultTableModel tabela = (DefaultTableModel) listadeprodutos.getModel();

//       if (!(qtd.isEmpty()&& !(idpeca.isEmpty()) == true || qtd  == null || idpeca.equals("") == true)) {
      // if (!(culturasSelecionadas.is&& !(prod.isEmpty()) == true || area  == null || area.equals("") == true)) {

         
                tabela.addRow(new String[1]);

                listadeprodutos.setValueAt(idproduto,listadeprodutos.getRowCount()-1, 0);
                listadeprodutos.setValueAt((((Produtos)comboproduto.getSelectedItem()).getProduto()),listadeprodutos.getRowCount()-1, 1);
                listadeprodutos.setValueAt(qtd,listadeprodutos.getRowCount()-1, 2);
       }
       
       private void cadastrarAulas(){
     try {
         Formacaoturma ft=new Formacaoturma();
          int selecionado = listaformando.getSelectedRow();
        //  int idEmp = Integer.valueOf(listaformando.getValueAt(selecionado, 0).toString());
           Formacaoturma f = new FormacaoturmaJpaController().findFormacaoturma(idEmp);
          ft.setIdformando(formando.getIdformando());
          ft.setIdformador(new Formador(((Formador)comboformador.getSelectedItem()).getIdformador()));
          ft.setIdmestre(new Mestre(((Mestre)combomestre.getSelectedItem()).getIdmestre()));
           if(!txthorasfreq1.getText().trim().equals("")){
               ft.setHorasmesprimeiro(new Float(txthorasfreq1.getText()));
            } else
                ft.setHorasmesprimeiro(new Float(0));
           
           if(!txthorasfreq2.getText().trim().equals("")){
               ft.setHorasmesegundo(new Float(txthorasfreq2.getText()));
            } else
                ft.setHorasmesegundo(new Float(0));
           
           if(!txthorasfreq3.getText().trim().equals("")){
               ft.setHorasmesterceiro(new Float(txthorasfreq3.getText()));
            } else
                ft.setHorasmesterceiro(new Float(0));
          if(!txthorasfalta1.getText().trim().equals("")){
               ft.setHorasfaltaprimeiro(new Float(txthorasfalta1.getText()));
            } else
                ft.setHorasfaltaprimeiro(new Float(0));
          if(!txthorasfalta2.getText().trim().equals("")){
               ft.setHorasfaltasegundo(new Float(txthorasfalta2.getText()));
            } else
                ft.setHorasfaltasegundo(new Float(0));
          
          if(!txthorasfalta3.getText().trim().equals("")){
               ft.setHorasfaltaterceiro(new Float(txthorasfalta3.getText()));
            } else
                ft.setHorasfaltaterceiro(new Float(0));
          
          
          ft.setDinicio(new Date((dinicio.getDate().getTime())));
          ft.setDfim(new Date((dfim.getDate().getTime())));
           if(aprovado.isSelected()){
              ft.setAprovacao(true);
          } else if(reprovado.isSelected()){
             ft.setAprovacao(false);
          }
            if(desistente.isSelected()){
              ft.setDesistencia(true);
          } else if(naodesistente.isSelected()){
             ft.setDesistencia(false);
          }
            
            if(!txtclassificacao.getText().trim().equals("")){
               ft.setClassificacao(new Integer(txtclassificacao.getText()));
            } else
                ft.setClassificacao(new Integer(0));
          
         
          
          FormacaoturmaJpaController ftjpa=new FormacaoturmaJpaController();
         // if(f.getIdformando()!=0){
          ftjpa.edit(ft);
          JOptionPane.showMessageDialog(null, "Actualizado com Sucesso"+ft.getIdformando());
          limparcampos();
        //  }else
//          {
//          JOptionPane.showMessageDialog(null,"Formando Registado", "Aviso", JOptionPane.WARNING_MESSAGE);
//          }
     } catch (IllegalOrphanException ex) {
         Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
     } catch (PreexistingEntityException ex) {
         Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
     } catch (Exception ex) {
         Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
     }
//       
       
       }
       
       private void verificarcampos(){
           if(idEmp==formando.getIdformando()){
             // txtnome.requestFocus();
              JOptionPane.showMessageDialog(null,"Não foi selecionado o formando", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
              if(dinicio.getDate().equals("")){
              dinicio.requestFocus();
              JOptionPane.showMessageDialog(null,"Data do inicio das aulas", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
            if(dfim.getDate().equals("")){
              dfim.requestFocus();
              JOptionPane.showMessageDialog(null,"Data do fim das aulas", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
           
            if(txthorasfreq1.getText().trim().equals("")){
              txthorasfreq1.requestFocus();
              JOptionPane.showMessageDialog(null,"Horas frequentadas no primeiro mes", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           } 
             if(txthorasfalta1.getText().trim().equals("")){
              txthorasfalta1.requestFocus();
              JOptionPane.showMessageDialog(null,"Horas faltas no primeiro mes", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
             if(txthorasfreq2.getText().trim().equals("")){
              txthorasfreq2.requestFocus();
              JOptionPane.showMessageDialog(null,"Horas frequentadas esta vazio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           } 
             if(txthorasfalta2.getText().trim().equals("")){
              txthorasfalta2.requestFocus();
              JOptionPane.showMessageDialog(null,"Horas faltas esta vazio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
             if(txthorasfreq3.getText().trim().equals("")){
              txthorasfreq3.requestFocus();
              JOptionPane.showMessageDialog(null,"Horas frequentadas esta vazio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           } 
             if(txthorasfalta3.getText().trim().equals("")){
              txthorasfalta3.requestFocus();
              JOptionPane.showMessageDialog(null,"Horas faltas esta vazio", "Aviso", JOptionPane.WARNING_MESSAGE);
              return;
           }
             
             cadastrarAulas();
           //  cadastrarprodutos();
             dispose();
           
       }
       
       private void limparcampos(){
         txtEstadoCivil.setText("");
         txtHabilitacoes.setText("");
         txtIdade.setText("");
         txtSexo.setText("");
         txtclassificacao.setText("");
         txthorasfalta1.setText("");
         txthorasfalta2.setText("");
         txthorasfalta3.setText("");
         txthorasfreq1.setText("");
         txthorasfreq2.setText("");
         txthorasfreq3.setText("");
         txtnome.setText("");
         txtocorrencias.setText("");
         txtquantidade.setText("");
         comboDistrito.setSelectedIndex(0);
         ComboLocalidade.setSelectedIndex(0);
         combocurso.setSelectedIndex(0);
         combomestre.setSelectedIndex(0);
         comboformador.setSelectedIndex(0);
         comboproduto.setSelectedIndex(0);
         reprovado.setSelected(true);
         naodesistente.setSelected(true);
         DefaultTableModel tabela = (DefaultTableModel) listadeprodutos.getModel();
         tabela.removeTableModelListener(listadeprodutos);
       
       
       
       
       }
       private void cadastrarprodutos(){
           Artigo a=new Artigo();
        
        
         if (listadeprodutos.getRowCount() > 0) {
                            for (int i = 0; i < listadeprodutos.getRowCount(); i++) {
                                try {                                                               
                                    a.setFormacaoturma(new Formacaoturma(formando.getIdformando()));
                                    a.setProdutos(new Produtos(Integer.valueOf(listadeprodutos.getValueAt(i, 0).toString())));
                                    a.setQuantidade(new Float(listadeprodutos.getValueAt(i, 2).toString()));
                                    a.setIdmes(new Mes(Integer.valueOf(combomes.getSelectedIndex()+1)));
                                    new ArtigoJpaController().edit(a);
                                } catch (PreexistingEntityException ex) {
                                    Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (Exception ex) {
                                    Logger.getLogger(ModificarTurma.class.getName()).log(Level.SEVERE, null, ex);
                                }
                           }
         }
   }
     private void prenchercampos(){
       //formando = new FormandoJpaController().findFormando(idEmp);
        txtnome.setText(formando.getFormando().getNome());
        txtIdade.setText(String.valueOf(formando.getFormando().getIdade()));
        txtEstadoCivil.setText(formando.getFormando().getIdestadocivil().getEstado());
        txtHabilitacoes.setText(formando.getFormando().getIdnivelhabilitacao().getNivelhabilitacao());
         if (formando.getFormando().getSexo()==true) 
                     txtSexo.setText("Masculino");
                     
                 else 
                 
                     txtSexo.setText("Feminino");
     
     
     txtclassificacao.setText(String.valueOf(formando.getClassificacao()));
     txthorasfalta1.setText(String.valueOf(formando.getHorasfaltaprimeiro()));
     txthorasfalta2.setText(String.valueOf(formando.getHorasfaltasegundo()));
     txthorasfalta3.setText(String.valueOf(formando.getHorasfaltaterceiro()));
     txthorasfreq1.setText(String.valueOf(formando.getHorasmesprimeiro()));
     txthorasfreq2.setText(String.valueOf(formando.getHorasmesegundo()));
     txthorasfreq3.setText(String.valueOf(formando.getHorasmesterceiro()));
     
     comboDistrito.setSelectedItem(formando.getFormando().getIdlocalidade().getIdposto().getIddistrito().getDistrito());
     ComboLocalidade.setSelectedItem(formando.getFormando().getIdlocalidade().getLocalidade());
     combocurso.setSelectedItem(formando.getFormando().getAreadeformacao().getIdcurso1().getCurso());
     comboformador.setSelectedItem(formando.getIdformador().getFormador());
     java.util.Date di = (java.util.Date)formando.getDinicio();
        dinicio.setDate(di);
     java.util.Date df = (java.util.Date)formando.getDfim();
        dfim.setDate(df);
     if (formando.getAprovacao()==true) 
                     aprovado.setSelected(true);
                     
                 else 
                 
                     reprovado.setSelected(true); 
     
      if (formando.getDesistencia()==true) 
                     desistente.setSelected(true);
                     
                 else 
                 
                     naodesistente.setSelected(true);   
     } 
      
     public void prencherproducao(){
  
//        
//        int curso = ((Curso)combocurso.getSelectedItem()).getIdcurso();
        List<Artigo> formandos = new ArtigoJpaController().prencherartigo(formando.getIdformando());

        DefaultTableModel tbm = (DefaultTableModel) listadeprodutos.getModel();

        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (Artigo f : formandos) {
            tbm.addRow(new String[1]);
 
            listadeprodutos.setValueAt(f.getProdutos().getIdproduto(), i, 0);
            listadeprodutos.setValueAt(f.getProdutos().getProduto(), i, 1);
            listadeprodutos.setValueAt(f.getQuantidade(), i, 2);
            listadeprodutos.setValueAt(f.getIdmes().getMes(), i, 3);
               


            i++;
        }
     
     } 
       
}
