/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Dao.DistritoDao;
import Dao.FormandoDao;
import Dao.LocalidadeDao;
import Dao.PostoDao;
import Modelo.Curso;
import Modelo.Cursoformacao;
import Modelo.Distrito;
import Modelo.Finscritos;
import Modelo.Formando;
import Modelo.Localidade;
import Modelo.Posto;
import Modelo.Relactividadecontapropria;
import Modelo.Relactividadeprof;
import Modelo.Relareaprioridade;
import Modelo.Relcasapropria;
import Modelo.Relchefefamilia;
import Modelo.Reldeficiente;
import Modelo.Reldiplocursoinefp;
import Modelo.Reldiplocursoprof;
import Modelo.Relempregocontaoutrem;
import Modelo.Relescalao;
import Modelo.Relestadocivil;
import Modelo.Relfaixaetaria;
import Modelo.Relfilhos;
import Modelo.Relfreqcursoprof;
import Modelo.Relhabilitacao;
import Modelo.Relnrformando;
import Modelo.Relrendimentodiario;
import Modelo.Relrendimentomes;
import Persistencia.CursoJpaController;
import Persistencia.DistritoJpaController;
import Persistencia.FinscritosJpaController;
import Persistencia.LocalidadeJpaController;
import java.beans.PropertyVetoException;
import java.io.File;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.table.DefaultTableModel;
import metodo.RelatorioCtr;
import metodo.RelatorioCurso;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author MASSINGUE
 */
public class RelatorioDoCurso extends javax.swing.JInternalFrame {

    /**
     * Creates new form GestaoFormando
     */
    public RelatorioDoCurso() {
        try {
            initComponents();
//            prenchercomboCurso();
//            prenchercomboDistrito();
//            prenchercomboLocalidade();
//            prenchercomboDistrito1();
//            prenchercomboLocalidade1();
            prenchercomboDistritoHL();

        } catch (SQLException ex) {
            Logger.getLogger(GestaoFormando.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel32 = new javax.swing.JPanel();
        jPanel40 = new javax.swing.JPanel();
        jPanel41 = new javax.swing.JPanel();
        ComboBoxpesquisadistritoHL = new javax.swing.JComboBox();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        ComboBoxpesquisalocalidadeHL = new javax.swing.JComboBox();
        jPanel42 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        listadeformandoHL = new javax.swing.JTable();
        jPanel43 = new javax.swing.JPanel();
        jPanel44 = new javax.swing.JPanel();
        btnImprimirHL = new javax.swing.JButton();
        btnGraficoHL = new javax.swing.JButton();

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setPreferredSize(new java.awt.Dimension(1344, 490));
        jPanel1.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                jPanel1AncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseReleased(evt);
            }
        });

        jPanel41.setBackground(new java.awt.Color(102, 204, 255));
        jPanel41.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        ComboBoxpesquisadistritoHL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisadistritoHLItemStateChanged(evt);
            }
        });

        jLabel16.setText("Distrito:");

        jLabel17.setText("Comunidade:");

        ComboBoxpesquisalocalidadeHL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboBoxpesquisalocalidadeHLItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel41Layout = new javax.swing.GroupLayout(jPanel41);
        jPanel41.setLayout(jPanel41Layout);
        jPanel41Layout.setHorizontalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(ComboBoxpesquisadistritoHL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel41Layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel16)))
                .addGap(20, 20, 20)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComboBoxpesquisalocalidadeHL, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel41Layout.setVerticalGroup(
            jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel41Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel41Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBoxpesquisadistritoHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ComboBoxpesquisalocalidadeHL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel42.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        listadeformandoHL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Curso", "Codigo Curso", "Matriculados H.", "Matriculados M.", "Total Matriculados", "Aprovados H.", "Aprovados M.", "Total Aprovados", "Reprovados H.", "Reprovados M", "Total Reprovados", "Desistentes H.", "Desistentes M.", "Total Desistentes", "Consumiveis", "EPI's", "Equipamentos", "Honorarios", "Orç. Toatal"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true, false, true, true, true, true, true, true, true, true, true, true, true, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listadeformandoHL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listadeformandoHLMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(listadeformandoHL);

        javax.swing.GroupLayout jPanel42Layout = new javax.swing.GroupLayout(jPanel42);
        jPanel42.setLayout(jPanel42Layout);
        jPanel42Layout.setHorizontalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 1305, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel42Layout.setVerticalGroup(
            jPanel42Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel42Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel43.setBackground(new java.awt.Color(0, 153, 255));
        jPanel43.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel44.setBackground(new java.awt.Color(0, 153, 255));

        btnImprimirHL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/print.png"))); // NOI18N
        btnImprimirHL.setText("Imprimir");
        btnImprimirHL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImprimirHLActionPerformed(evt);
            }
        });

        btnGraficoHL.setText("Grafico");
        btnGraficoHL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficoHLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel44Layout = new javax.swing.GroupLayout(jPanel44);
        jPanel44.setLayout(jPanel44Layout);
        jPanel44Layout.setHorizontalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel44Layout.createSequentialGroup()
                .addComponent(btnImprimirHL, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGraficoHL, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1084, Short.MAX_VALUE))
        );
        jPanel44Layout.setVerticalGroup(
            jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel44Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel44Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnImprimirHL)
                    .addComponent(btnGraficoHL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel43Layout = new javax.swing.GroupLayout(jPanel43);
        jPanel43.setLayout(jPanel43Layout);
        jPanel43Layout.setHorizontalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel44, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel43Layout.setVerticalGroup(
            jPanel43Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel43Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jPanel44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel40Layout = new javax.swing.GroupLayout(jPanel40);
        jPanel40.setLayout(jPanel40Layout);
        jPanel40Layout.setHorizontalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel41, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel42, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel40Layout.setVerticalGroup(
            jPanel40Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel40Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jPanel41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel32Layout = new javax.swing.GroupLayout(jPanel32);
        jPanel32.setLayout(jPanel32Layout);
        jPanel32Layout.setHorizontalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1330, Short.MAX_VALUE)
            .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel32Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel32Layout.setVerticalGroup(
            jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 464, Short.MAX_VALUE)
            .addGroup(jPanel32Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel32Layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Curso por Comunidade", jPanel32);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1332, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 492, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel1AncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_jPanel1AncestorAdded
        try {
            this.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jPanel1AncestorAdded

    private void jTabbedPane1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseReleased

//        if (jTabbedPane1.getSelectedIndex() == 2) {
//            try {
//                prenchercomboDistritoAP();
//            } catch (SQLException ex) {
//                Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            //            try {
//                //                prenchercomboLocalidadeAP();
//                //            } catch (SQLException ex) {
//                //                Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
//                //            }
//            //  listarRelactividadeprof();
//        } else if (jTabbedPane1.getSelectedIndex() == 3) {
//            try {
//                prenchercomboDistritoFE();
//            } catch (SQLException ex) {
//                Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
//            }
//            //            try {
//                //                prenchercomboLocalidadeFE();
//                //            } catch (SQLException ex) {
//                //                Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
//                //            }
//            //  listarRelfaixaetaria();
//        }
    }//GEN-LAST:event_jTabbedPane1MouseReleased

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
       
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void btnGraficoHLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficoHLActionPerformed
        
        Localidade l = null;
        if (ComboBoxpesquisalocalidadeHL.getSelectedIndex() != 0) {
            l = (Localidade) ComboBoxpesquisalocalidadeHL.getSelectedItem();
        }
        List<Cursoformacao> le = new RelatorioCurso().getCursoformacaoLocalidade(l);
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(le);
        // String path = "/relatorios/recibov.jasper";
        JasperPrint jpPrint = null;
        JasperViewer jv;
        Map par = new HashMap<>();
        // par.put("tf", total);
        par.put("distrito",((Distrito) ComboBoxpesquisadistritoHL.getSelectedItem()).getDistrito());
        par.put("comunidade",((Localidade) ComboBoxpesquisalocalidadeHL.getSelectedItem()).getLocalidade());

        //String path = "C:\\Users\\Ussimane\\Desktop\\tree\\src\\Relatorio\\relHLgraf.jasper";
        String path = new File("Relatorio/relCursograf.jasper").getAbsolutePath();
        String img = new File("Icone/logonoruega.png").getAbsolutePath();
        par.put("img", img);
        try {
            jpPrint = JasperFillManager.fillReport(path, par, ds);//new metodos.ControllerAcess().conetion());
        } catch (JRException ex) {
            Logger.getLogger(GerirFormando.class.getName()).log(Level.SEVERE, null, ex);
        }
        jv = new JasperViewer(jpPrint, false); //O false eh para nao fechar a aplicacao
        JDialog viewer = new JDialog(new javax.swing.JFrame(), "Grafico - Curso por comunidade", true);
        viewer.setSize(1024, 768);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);
    }//GEN-LAST:event_btnGraficoHLActionPerformed

    private void btnImprimirHLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImprimirHLActionPerformed
        
        Localidade l = null;
        if (ComboBoxpesquisalocalidadeHL.getSelectedIndex() != 0) {
            l = (Localidade) ComboBoxpesquisalocalidadeHL.getSelectedItem();
        }
        List<Cursoformacao> le = new RelatorioCurso().getCursoformacaoLocalidade(l);
        JRBeanCollectionDataSource ds = new JRBeanCollectionDataSource(le);
        // String path = "/relatorios/recibov.jasper";
        JasperPrint jpPrint = null;
        JasperViewer jv;
        Map par = new HashMap<>();
        // par.put("tf", total);

        //String path = "C:\\Users\\Ussimane\\Desktop\\tree\\src\\Relatorio\\relHL.jasper";
        String path = new File("Relatorio/relCurso.jasper").getAbsolutePath();
        String img = new File("Icone/logonoruega.png").getAbsolutePath();
        par.put("img", img);
        par.put("distrito",((Distrito) ComboBoxpesquisadistritoHL.getSelectedItem()).getDistrito());
        par.put("comunidade",((Localidade) ComboBoxpesquisalocalidadeHL.getSelectedItem()).getLocalidade());
        try {
            jpPrint = JasperFillManager.fillReport(path, par, ds);//new metodos.ControllerAcess().conetion());
        } catch (JRException ex) {
            Logger.getLogger(GerirFormando.class.getName()).log(Level.SEVERE, null, ex);
        }
        jv = new JasperViewer(jpPrint, false); //O false eh para nao fechar a aplicacao
        JDialog viewer = new JDialog(new javax.swing.JFrame(), "Curso por comunidade", true);
        viewer.setSize(1024, 768);
        viewer.setLocationRelativeTo(null);
        viewer.getContentPane().add(jv.getContentPane());
        viewer.setVisible(true);
    }//GEN-LAST:event_btnImprimirHLActionPerformed

    private void listadeformandoHLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listadeformandoHLMouseClicked

    }//GEN-LAST:event_listadeformandoHLMouseClicked

    private void ComboBoxpesquisalocalidadeHLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisalocalidadeHLItemStateChanged
        listarRelHL();
    }//GEN-LAST:event_ComboBoxpesquisalocalidadeHLItemStateChanged

    private void ComboBoxpesquisadistritoHLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboBoxpesquisadistritoHLItemStateChanged
        try {
            prenchercomboLocalidadeHL();
        } catch (SQLException ex) {
            Logger.getLogger(Relatorio.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ComboBoxpesquisadistritoHLItemStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBoxpesquisadistritoHL;
    private javax.swing.JComboBox ComboBoxpesquisalocalidadeHL;
    private javax.swing.JButton btnGraficoHL;
    private javax.swing.JButton btnImprimirHL;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel32;
    private javax.swing.JPanel jPanel40;
    private javax.swing.JPanel jPanel41;
    private javax.swing.JPanel jPanel42;
    private javax.swing.JPanel jPanel43;
    private javax.swing.JPanel jPanel44;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable listadeformandoHL;
    // End of variables declaration//GEN-END:variables

     private void prenchercomboDistritoHL() throws SQLException {

        List<Distrito> distritos = new DistritoJpaController().findDistritoEntities();
        ComboBoxpesquisadistritoHL.removeAllItems();
        ComboBoxpesquisadistritoHL.addItem("--Distrito--");
        for (Distrito d : distritos) {
            ComboBoxpesquisadistritoHL.addItem(d);
        }
        if (!distritos.isEmpty()) {
            ComboBoxpesquisadistritoHL.setSelectedIndex(0);
        }

    }
    private void prenchercomboLocalidadeHL() throws SQLException {
        List<Localidade> comunidades = new ArrayList<Localidade>();
        if (ComboBoxpesquisadistritoHL.getSelectedItem() == null) {
            return;
        }
        if (ComboBoxpesquisadistritoHL.getSelectedIndex() != 0) {
            comunidades = new LocalidadeDao().mostrarLocalidade(((Distrito) ComboBoxpesquisadistritoHL.getSelectedItem()).getIddistrito());
        }
        ComboBoxpesquisalocalidadeHL.removeAllItems();
        ComboBoxpesquisalocalidadeHL.addItem("--Localidade--");
        for (Localidade p : comunidades) {
            ComboBoxpesquisalocalidadeHL.addItem(p);
        }
    }

    public void listarRelHL() {

        Localidade l = null;
        if (ComboBoxpesquisalocalidadeHL.getSelectedIndex() != 0) {
            l = (Localidade) ComboBoxpesquisalocalidadeHL.getSelectedItem();
        }
        List<Cursoformacao> lcf = new RelatorioCurso().getCursoformacaoLocalidade(l);

        DefaultTableModel tbm = (DefaultTableModel) listadeformandoHL.getModel();

        for (int i = tbm.getRowCount() - 1; i >= 0; i--) {
            tbm.removeRow(i);
        }
        int i = 0;
        for (Cursoformacao f : lcf) {
            tbm.addRow(new String[1]);

            listadeformandoHL.setValueAt(f.getIdcurso().getCurso(), i, 0);
            listadeformandoHL.setValueAt(f.getCodcurso(), i, 1);
            listadeformandoHL.setValueAt(f.getMatriculadoH(), i, 2);
//                     listadeformando.setValueAt(f.getSexo(), i, 2);
            listadeformandoHL.setValueAt(f.getMatriculadoM(), i, 3);
            listadeformandoHL.setValueAt(f.getTotalmatriculado(), i, 4);
            listadeformandoHL.setValueAt(f.getFormadosH(), i, 5);
            listadeformandoHL.setValueAt(f.getFormadosM(), i, 6);
            listadeformandoHL.setValueAt(f.getTotalformados(), i, 7);
            listadeformandoHL.setValueAt(f.getReprovadoH(), i, 8);
            listadeformandoHL.setValueAt(f.getReprovadoM(), i, 9);
            listadeformandoHL.setValueAt(f.getTotalreprovados(), i, 10);
            listadeformandoHL.setValueAt(f.getDesistenteH(), i, 11);
            listadeformandoHL.setValueAt(f.getDesistenteM(), i, 12);
            listadeformandoHL.setValueAt(f.getTotaldesistente(), i, 13);
            listadeformandoHL.setValueAt(f.getOrcamentoconsumiveis(), i, 14);
            listadeformandoHL.setValueAt(f.getOrcamentoepi(), i, 15);
            listadeformandoHL.setValueAt(f.getOrcamentoequipamento(), i, 16);
            listadeformandoHL.setValueAt(f.getOrcamentohonorario(), i, 17);
            listadeformandoHL.setValueAt(f.getOrcamentoconsumiveis()+f.getOrcamentoepi()
                    +f.getOrcamentoequipamento()+f.getOrcamentoconsumiveis(), i, 18);
            i++;
        }

    }
}
